DATALAKE.MS_UDEMY_FILES.STG_UDEMY_FILESDATALAKE.MS_UDEMY_FILES.STG_UDEMY_FILESDATALAKE.MS_UDEMY_FILES.STG_UDEMY_FILES-- Use the main role for now; later you can create a separate role/user

USE ROLE ACCOUNTADMIN;

-- 1) Warehouse (compute)
CREATE OR REPLACE WAREHOUSE WH_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE DATALAKE;

------------------------------------------------------------------------------------------------------------------------------

USE DATABASE DATALAKE;
CREATE SCHEMA IF NOT EXISTS UDEMY_FILES;
USE SCHEMA UDEMY_FILES;

CREATE OR REPLACE FILE FORMAT FF_CSV
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('', 'NULL');

CREATE OR REPLACE STAGE STG_UDEMY_FILES
FILE_FORMAT = FF_CSV;

-----------------------------------------------------------------------------------------------------------------------------
-- Upload the Files to the internal stage
-----------------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TABLE DATALAKE.UDEMY_FILES.CALENDAR_LOOKUP (
  "Date" DATE
);

CREATE OR REPLACE TABLE DATALAKE.UDEMY_FILES.CUSTOMER_LOOKUP (
  CustomerKey      NUMBER,
  Prefix           STRING,
  FirstName        STRING,
  LastName         STRING,
  BirthDate        DATE,
  MaritalStatus    STRING,
  Gender           STRING,
  EmailAddress     STRING,
  AnnualIncome     NUMBER,
  TotalChildren    NUMBER,
  EducationLevel   STRING,
  Occupation       STRING,
  HomeOwner        STRING
);

CREATE OR REPLACE TABLE DATALAKE.UDEMY_FILES.PRODUCT_LOOKUP (
  ProductKey            NUMBER,
  ProductSubcategoryKey NUMBER,
  ProductSKU            STRING,
  ProductName           STRING,
  ModelName             STRING,
  ProductDescription    STRING,
  ProductColor          STRING,
  ProductSize           STRING,
  ProductStyle          STRING,
  ProductCost           NUMBER(19,4),
  ProductPrice          NUMBER(19,4)
);

CREATE OR REPLACE TABLE DATALAKE.UDEMY_FILES.PRODUCT_CATEGORIES_LOOKUP (
  ProductCategoryKey NUMBER,
  CategoryName       STRING
);

CREATE OR REPLACE TABLE DATALAKE.UDEMY_FILES.PRODUCT_SUB_CATEGORIES_LOOKUP (
  ProductSubcategoryKey NUMBER,
  SubcategoryName       STRING,
  ProductCategoryKey    NUMBER
);

CREATE OR REPLACE TABLE DATALAKE.UDEMY_FILES.TERRITORY_LOOKUP (
  SalesTerritoryKey NUMBER,
  Region            STRING,
  Country           STRING,
  Continent         STRING
);

CREATE OR REPLACE TABLE DATALAKE.UDEMY_FILES.RETURNS_DATA (
  ReturnDate      DATE,
  TerritoryKey    NUMBER,
  ProductKey      NUMBER,
  ReturnQuantity  NUMBER
);

CREATE OR REPLACE TABLE DATALAKE.UDEMY_FILES.SALES_FACT (
    OrderDate        DATE,
    StockDate        DATE,
    OrderNumber      STRING,
    ProductKey       NUMBER,
    CustomerKey      NUMBER,
    TerritoryKey     NUMBER,
    OrderLineItem    NUMBER,
    OrderQuantity    NUMBER
);

COPY INTO DATALAKE.UDEMY_FILES.CUSTOMER_LOOKUP
FROM @STG_UDEMY_FILES/AdventureWorksCustomerLookup.csv
FILE_FORMAT = FF_CSV
ON_ERROR = 'CONTINUE';

COPY INTO DATALAKE.UDEMY_FILES.CALENDAR_LOOKUP
FROM @STG_UDEMY_FILES/AdventureWorksCalendarLookup.csv
FILE_FORMAT = FF_CSV
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO DATALAKE.UDEMY_FILES.PRODUCT_LOOKUP
FROM @STG_UDEMY_FILES/AdventureWorksProductLookup.csv
FILE_FORMAT = FF_CSV
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO DATALAKE.UDEMY_FILES.PRODUCT_CATEGORIES_LOOKUP
FROM @STG_UDEMY_FILES/AdventureWorksProductCategoriesLookup.csv
FILE_FORMAT = FF_CSV
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO DATALAKE.UDEMY_FILES.PRODUCT_SUB_CATEGORIES_LOOKUP
FROM @STG_UDEMY_FILES/AdventureWorksProductSubcategoriesLookup.csv
FILE_FORMAT = FF_CSV
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO DATALAKE.UDEMY_FILES.TERRITORY_LOOKUP
FROM @STG_UDEMY_FILES/AdventureWorksTerritoryLookup.csv
FILE_FORMAT = FF_CSV
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO DATALAKE.UDEMY_FILES.RETURNS_DATA
FROM @STG_UDEMY_FILES/AdventureWorksReturnsData.csv
FILE_FORMAT = FF_CSV
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO DATALAKE.UDEMY_FILES.SALES_FACT
FROM @STG_UDEMY_FILES
PATTERN = '.*AdventureWorks Sales Data 202[0-2]\.csv(\.gz)?'
FILE_FORMAT = FF_CSV
ON_ERROR = 'ABORT_STATEMENT';


ALTER SCHEMA DATALAKE.UDEMY_FILES RENAME TO DATALAKE.MS_UDEMY_FILES;


------------------------------------------------------------------------------------------------------------------------------

-- After loading the Related dimensions in AdventureWorksDW2022 to Snowflake

SELECT
    COALESCE(ms.table_name, ud.table_name)        AS TABLE_NAME,

    ms.table_name                                 AS MS_ADWDW2022_DBO_TABLE_NAME,
    ms.row_count                                  AS MS_ADWDW2022_DBO_ROW_COUNT,

    ud.table_name                                 AS UDEMY_FILES_TABLE_NAME,
    ud.row_count                                  AS UDEMY_FILES_ROW_COUNT
FROM (
    SELECT
        table_name,
        row_count
    FROM DATALAKE.INFORMATION_SCHEMA.TABLES
    WHERE table_schema = 'MS_ADWDW2022_DBO'
      AND table_type = 'BASE TABLE'
) ms
FULL OUTER JOIN (
    SELECT
        table_name,
        row_count
    FROM DATALAKE.INFORMATION_SCHEMA.TABLES
    WHERE table_schema = 'UDEMY_FILES'
      AND table_type = 'BASE TABLE'
) ud
ON ms.table_name = ud.table_name
ORDER BY TABLE_NAME;

------------------------------------------------------------------------------------------------------------------------------

-- Query to create Table DEMOGRAPHICS.

CREATE OR REPLACE TABLE DATALAKE.MS_PERSON.DEMOGRAPHICS AS
SELECT
  e.BUSINESSENTITYID,
  -- e.EMAILADDRESSID, 
  c.EMAILADDRESS,

  -- Keep demographic fields from DimCustomer
  c.CUSTOMERALTERNATEKEY,
  c.BIRTHDATE,
  c.MARITALSTATUS,
  c.GENDER,
  c.YEARLYINCOME,
  c.TOTALCHILDREN,
  c.ENGLISHEDUCATION,
  c.ENGLISHOCCUPATION,
  c.HOUSEOWNERFLAG,
  
FROM DATALAKE.MS_ADWDW2022_DBO.DIMCUSTOMER c
LEFT JOIN DATALAKE.MS_PERSON.EMAILADDRESS e
  ON UPPER(TRIM(c.EMAILADDRESS)) = UPPER(TRIM(e.EMAILADDRESS));

  
SELECT * FROM DATALAKE.MS_PERSON.DEMOGRAPHICS; ---> 18484

-- Analysis:

SELECT * FROM DATALAKE.MS_PERSON.EMAILADDRESS; ---> 19972
SELECT * FROM DATALAKE.MS_ADWDW2022_DBO.DIMCUSTOMER; ---> 18484
DESC TABLE DATALAKE.MS_ADWDW2022_DBO.DIMCUSTOMER;
DESC TABLE DATALAKE.MS_PERSON.EMAILADDRESS;


SELECT COUNT(*) FROM MS_ADWDW2022_DBO.DIMCUSTOMER;
SELECT
  COUNT(*) AS total_rows,
  COUNT_IF(EMAILADDRESS IS NULL OR TRIM(EMAILADDRESS) = '') AS missing_email
FROM MS_ADWDW2022_DBO.DIMCUSTOMER;

SELECT
  UPPER(TRIM(EMAILADDRESS)) AS email_norm,
  COUNT(*) AS cnt
FROM MS_PERSON.EMAILADDRESS
WHERE EMAILADDRESS IS NOT NULL AND TRIM(EMAILADDRESS) <> ''
GROUP BY 1
HAVING COUNT(*) > 1
ORDER BY cnt DESC;

SELECT
  COUNT(*) AS total_customers,
  COUNT_IF(e.BUSINESSENTITYID IS NOT NULL) AS matched_customers,
  COUNT_IF(e.BUSINESSENTITYID IS NULL) AS unmatched_customers
FROM DATALAKE.MS_ADWDW2022_DBO.DIMCUSTOMER c
LEFT JOIN DATALAKE.MS_PERSON.EMAILADDRESS e
  ON UPPER(TRIM(c.EMAILADDRESS)) = UPPER(TRIM(e.EMAILADDRESS));


SELECT COUNT(*)
FROM DATALAKE.MS_ADWDW2022_DBO.DIMCUSTOMER c
LEFT JOIN DATALAKE.MS_PERSON.EMAILADDRESS e
  ON c.EMAILADDRESS = e.EMAILADDRESS;

SELECT COUNT(*)
FROM DATALAKE.MS_ADWDW2022_DBO.DIMCUSTOMER c
left JOIN DATALAKE.MS_PERSON.EMAILADDRESS e
  ON UPPER(TRIM(c.EMAILADDRESS)) = UPPER(TRIM(e.EMAILADDRESS));



SELECT COUNT(*) FROM UDEMY_FILES.CUSTOMER_LOOKUP ----> 18149
-- BIRTHDATE, MARITALSTATUS, GENDER, ANNUALINCOME, TOTALCHILDREN, ENGLISHEDUCATION (EDUCATIONLEVEL), ENGLISHOCCUPATION (OCCUPATION), HOUSEOWNERFLAG (HOMEOWNER)

----------------------------------------------------------------------------------------------------------------------------------



-- Preparing UDEMYSALES and UDEMYRETURNS.
CREATE OR REPLACE TABLE DATALAKE.MS_SALES.UDEMYSALES AS

SELECT FACT_SALES.ORDERDATE, FACT_SALES.STOCKDATE, FACT_SALES.ORDERNUMBER, 
-- FACT_SALES.PRODUCTKEY, FACT_SALES.CUSTOMERKEY, FACT_SALES.TERRITORYKEY, DIM_TERR.SALESTERRITORYREGION, DIM_CUST.EMAILADDRESS,
DIM_PROD.PRODUCTALTERNATEKEY, PROD.PRODUCTID, EMAIL.BUSINESSENTITYID AS CUSTOMERID, TERR.TERRITORYID, FACT_SALES.ORDERLINEITEM, FACT_SALES.ORDERQUANTITY
FROM DATALAKE.MS_UDEMY_FILES.SALES_FACT AS FACT_SALES

LEFT JOIN DATALAKE.MS_ADWDW2022_DBO.DIMPRODUCT AS DIM_PROD
ON FACT_SALES.PRODUCTKEY = DIM_PROD.PRODUCTKEY
LEFT JOIN DATALAKE.MS_PRODUCTION.PRODUCT AS PROD
ON DIM_PROD.PRODUCTALTERNATEKEY = PROD.PRODUCTNUMBER

LEFT JOIN DATALAKE.MS_ADWDW2022_DBO.DIMCUSTOMER AS DIM_CUST
ON FACT_SALES.CUSTOMERKEY = DIM_CUST.CUSTOMERKEY
LEFT JOIN DATALAKE.MS_PERSON.EMAILADDRESS AS EMAIL
ON TRIM(DIM_CUST.EMAILADDRESS) = TRIM(EMAIL.EMAILADDRESS)

LEFT JOIN DATALAKE.MS_ADWDW2022_DBO.DIMSALESTERRITORY AS DIM_TERR
ON FACT_SALES.TERRITORYKEY = DIM_TERR.SALESTERRITORYKEY
LEFT JOIN DATALAKE.MS_SALES.SALESTERRITORY AS TERR
ON DIM_TERR.SALESTERRITORYREGION = TERR.NAME;

SELECT * FROM DATALAKE.MS_SALES.UDEMYSALES;


CREATE OR REPLACE TABLE DATALAKE.MS_SALES.UDEMYRETURNS AS
SELECT 
FACT_RETURNS.RETURNDATE, PROD.PRODUCTID, TERR.TERRITORYID, FACT_RETURNS.RETURNQUANTITY
-- FACT_RETURNS.PRODUCTKEY, DIM_PROD.PRODUCTALTERNATEKEY, FACT_RETURNS.TERRITORYKEY, DIM_TERR.SALESTERRITORYREGION
FROM DATALAKE.MS_UDEMY_FILES.RETURNS_DATA AS FACT_RETURNS

LEFT JOIN DATALAKE.MS_ADWDW2022_DBO.DIMPRODUCT AS DIM_PROD
ON FACT_RETURNS.PRODUCTKEY = DIM_PROD.PRODUCTKEY
LEFT JOIN DATALAKE.MS_PRODUCTION.PRODUCT AS PROD
ON DIM_PROD.PRODUCTALTERNATEKEY = PROD.PRODUCTNUMBER

LEFT JOIN DATALAKE.MS_ADWDW2022_DBO.DIMSALESTERRITORY AS DIM_TERR
ON FACT_RETURNS.TERRITORYKEY = DIM_TERR.SALESTERRITORYKEY
LEFT JOIN DATALAKE.MS_SALES.SALESTERRITORY AS TERR
ON DIM_TERR.SALESTERRITORYREGION = TERR.NAME;

SELECT * FROM DATALAKE.MS_SALES.UDEMYRETURNS;

-- Analysis

SELECT COUNT(*) FROM UDEMY_FILES.SALES_FACT -- 56046
SELECT COUNT(*) FROM UDEMY_FILES.RETURNS_DATA -- 1809


SELECT * FROM DATALAKE.MS_SALES.UDEMYSALES -- 56046
SELECT * FROM DATALAKE.MS_SALES.UDEMYRETURNS -- 1809

----------------------------------------------------------------------------------------------------------------------------------
-- Exporting the UDEMYSALES and UDEMYRETURNS

USE DATABASE DATALAKE;
USE SCHEMA MS_SALES;

COPY INTO @~/export_udemysales
FROM DATALAKE.MS_SALES.UDEMYSALES
FILE_FORMAT = (
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
OVERWRITE = TRUE
SINGLE = TRUE;

COPY INTO @~/export_udemyreturns
FROM DATALAKE.MS_SALES.UDEMYRETURNS
FILE_FORMAT = (
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
OVERWRITE = TRUE
SINGLE = TRUE;

----------------------------------------------------------------------------------------------------------------------------------

-- Creating Calendar Table and loading the date from Jan 1st 2020 to June 30 2022
USE DATABASE DATALAKE;

CREATE SCHEMA IF NOT EXISTS DATALAKE.MS_DATE;

CREATE OR REPLACE TABLE DATALAKE.MS_DATE.CALENDAR (
    CALENDAR_DATE DATE
);

INSERT INTO DATALAKE.MS_DATE.CALENDAR (CALENDAR_DATE)
SELECT
    DATEADD(
        DAY,
        SEQ4(),
        '2019-01-01'::DATE
    ) AS CALENDAR_DATE
FROM TABLE(
    GENERATOR(ROWCOUNT => 1700)
);

SELECT * FROM DATALAKE.MS_DATE.CALENDAR;
----------------------------------------------------------------------------------------------------------------------------------

-- Strucute of our DataWarehouse

CREATE OR REPLACE DATABASE STAGE;
USE DATABASE STAGE;

CREATE SCHEMA IF NOT EXISTS MS_ADWBI;

CREATE OR REPLACE DATABASE DATA_ACCESS;
USE DATABASE DATA_ACCESS;
CREATE SCHEMA IF NOT EXISTS MS_ADWBI;

CREATE OR REPLACE DATABASE MS_ADWBI;
USE DATABASE MS_ADWBI;
CREATE SCHEMA IF NOT EXISTS WORK;
CREATE SCHEMA IF NOT EXISTS CTRL;

----------------------------------------------------------------------------------------------------------------------------------

-- Creating Views in DATA_ACCESS From DATALAKE for Adventure Works Data

CREATE OR REPLACE PROCEDURE DATA_ACCESS.PUBLIC.CREATE_DATA_ACCESS_VIEWS_FROM_DATALAKE_MS()
RETURNS STRING
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
var SRC_DB = "DATALAKE";
var TGT_DB = "DATA_ACCESS";

// Pick only schemas that literally start with MS_
var listSql = `
  SELECT TABLE_SCHEMA, TABLE_NAME
  FROM ${SRC_DB}.INFORMATION_SCHEMA.TABLES
  WHERE TABLE_TYPE = 'BASE TABLE'
    AND LEFT(TABLE_SCHEMA, 3) = 'MS_'
  ORDER BY TABLE_SCHEMA, TABLE_NAME
`;

var rs = snowflake.createStatement({sqlText: listSql}).execute();
var viewCount = 0;
var schemaSet = {};

while (rs.next()) {
  var sch = rs.getColumnValue(1);
  var tbl = rs.getColumnValue(2);

  // create target schema once
  if (!schemaSet[sch]) {
    snowflake.createStatement({
      sqlText: `CREATE SCHEMA IF NOT EXISTS ${TGT_DB}."${sch}"`
    }).execute();
    schemaSet[sch] = true;
  }

  // create or replace view
  snowflake.createStatement({
    sqlText: `CREATE OR REPLACE VIEW ${TGT_DB}."${sch}"."V_${tbl}DATA_ACCESS" AS
              SELECT * FROM ${SRC_DB}."${sch}"."${tbl}"`
  }).execute();

  viewCount++;
}

return `Created/Replaced ${viewCount} views in ${TGT_DB} from ${SRC_DB} (schemas starting with MS_).`;
$$;

CALL DATA_ACCESS.PUBLIC.CREATE_DATA_ACCESS_VIEWS_FROM_DATALAKE_MS();


SELECT * FROM DATA_ACCESS.MS_PERSON.V_DEMOGRAPHICS;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Queries to Load the Data to Stage from Source (DATA_ACCESS)

-- STG_CUSTOMER
CREATE OR REPLACE TABLE STAGE.MS_ADWBI.STG_CUSTOMER AS
SELECT
  p.BUSINESSENTITYID   AS BusinessEntityID,
  p.TITLE              AS Prefix,
  p.FIRSTNAME          AS FirstName,
  p.LASTNAME           AS LastName,
  d.BIRTHDATE          AS BirthDate,
  d.MARITALSTATUS      AS MaritalStatus,
  d.GENDER             AS Gender,
  e.EMAILADDRESS       AS EmailAddress,
  d.YEARLYINCOME       AS AnnualIncome,
  d.TOTALCHILDREN      AS TotalChildren,
  d.ENGLISHEDUCATION   AS EducationLevel,
  d.ENGLISHOCCUPATION  AS Occupation,
  d.HOUSEOWNERFLAG     AS HomeOwner
FROM DATA_ACCESS.MS_PERSON.V_PERSON p
LEFT JOIN DATA_ACCESS.MS_PERSON.V_EMAILADDRESS e
  ON e.BUSINESSENTITYID = p.BUSINESSENTITYID
LEFT JOIN DATA_ACCESS.MS_PERSON.V_DEMOGRAPHICS d
  ON d.BUSINESSENTITYID = p.BUSINESSENTITYID;


-- STG_PRODUCT
CREATE OR REPLACE TABLE STAGE.MS_ADWBI.STG_PRODUCT AS
SELECT
  p.PRODUCTID      AS ProductID,
  p.PRODUCTMODELID AS ProductModelID,
  p.productsubcategoryid AS PRODUCTSUBCATEGORYID,
  p.PRODUCTNUMBER  AS ProductSKU,
  p.NAME           AS ProductName,
  pm.NAME          AS ModelName,
  pd.DESCRIPTION   AS ProductDescription,
  p.COLOR          AS ProductColor,
  p.SIZE           AS ProductSize,
  p.STYLE          AS ProductStyle,
  p.STANDARDCOST   AS ProductCost,
  p.LISTPRICE      AS ProductPrice
FROM DATA_ACCESS.MS_PRODUCTION.V_PRODUCT p
LEFT JOIN DATA_ACCESS.MS_PRODUCTION.V_PRODUCTMODEL pm
  ON pm.PRODUCTMODELID = p.PRODUCTMODELID
LEFT JOIN DATA_ACCESS.MS_PRODUCTION.V_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE pmpd
  ON pmpd.PRODUCTMODELID = p.PRODUCTMODELID
LEFT JOIN DATA_ACCESS.MS_PRODUCTION.V_PRODUCTDESCRIPTION pd
  ON pd.PRODUCTDESCRIPTIONID = pmpd.PRODUCTDESCRIPTIONID
  WHERE pd.PRODUCTDESCRIPTIONID < 1218;


-- STG_PRODUCT_CATEGORY
CREATE OR REPLACE TABLE STAGE.MS_ADWBI.STG_PRODUCT_CATEGORY AS
SELECT
  PRODUCTCATEGORYID AS ProductCategoryID,
  NAME AS CategoryName
FROM DATA_ACCESS.MS_PRODUCTION.V_PRODUCTCATEGORY;


-- STG_PRODUCT_SUBCATEGORY
CREATE OR REPLACE TABLE STAGE.MS_ADWBI.STG_PRODUCT_SUBCATEGORY AS
SELECT
  PRODUCTSUBCATEGORYID AS ProductSubCategoryID,
  PRODUCTCATEGORYID AS ProductCategoryID,
  NAME AS SubcategoryName
FROM DATA_ACCESS.MS_PRODUCTION.V_PRODUCTSUBCATEGORY;

-- STG_TERRITORY
CREATE OR REPLACE TABLE STAGE.MS_ADWBI.STG_TERRITORY AS
SELECT
  st.TERRITORYID AS TerritoryID,
  st.NAME        AS Region,
  cr.NAME        AS Country,
  st."GROUP"     AS Continent
FROM DATA_ACCESS.MS_SALES.V_SALESTERRITORY st
LEFT JOIN DATA_ACCESS.MS_PERSON.V_COUNTRYREGION cr
  ON cr.COUNTRYREGIONCODE = st.COUNTRYREGIONCODE;

-- STG_CALENDAR
CREATE OR REPLACE TABLE STAGE.MS_ADWBI.STG_CALENDAR AS
SELECT CALENDAR_DATE AS Date FROM DATA_ACCESS.MS_DATE.V_CALENDAR;

SELECT * FROM STAGE.MS_ADWBI.STG_CALENDAR;

SELECT T.table_catalog, T.table_schema, T.table_name, C.COLUMN_NAME, C.data_type FROM STAGE.INFORMATION_SCHEMA.COLUMNS C
LEFT JOIN STAGE.INFORMATION_SCHEMA.TABLES T
ON C.TABLE_SCHEMA = T.TABLE_SCHEMA  AND C.TABLE_NAME = T.TABLE_NAME
WHERE T.TABLE_TYPE = 'BASE TABLE'
ORDER BY
    c.TABLE_SCHEMA,
    c.TABLE_NAME


SELECT * FROM STAGE.MS_ADWBI.STG_PRODUCT_CATEGORIES

-- STAGE FACT SALES

CREATE OR REPLACE TABLE STAGE.MS_ADWBI.STG_FACT_SALES AS
SELECT
  ORDERDATE::DATE           AS ORDERDATE,
  STOCKDATE::DATE           AS STOCKDATE,
  ORDERNUMBER               AS ORDERNUMBER,
  PRODUCTID::NUMBER(38,0)   AS PRODUCTID,
  CUSTOMERID::NUMBER(38,0) AS BUSINESSENTITYID,
  TERRITORYID::NUMBER(38,0) AS TERRITORYID,
  ORDERLINEITEM::NUMBER(38,0) AS ORDERLINEITEM,
  ORDERQUANTITY::NUMBER(38,0) AS ORDERQUANTITY,
  CURRENT_TIMESTAMP()       AS STG_LOAD_TS
FROM DATA_ACCESS.MS_SALES.V_UDEMYSALES;

SELECT * FROM STAGE.MS_ADWBI.STG_FACT_SALES;

-- STAGE FACT RETURNS

CREATE OR REPLACE TABLE STAGE.MS_ADWBI.STG_FACT_RETURNS AS
SELECT
  RETURNDATE::DATE          AS RETURNDATE,
  PRODUCTID::NUMBER(38,0)   AS PRODUCTID,
  TERRITORYID::NUMBER(38,0) AS TERRITORYID,
  RETURNQUANTITY::NUMBER(38,0) AS RETURNQUANTITY,
  CURRENT_TIMESTAMP()       AS STG_LOAD_TS
FROM DATA_ACCESS.MS_SALES.V_UDEMYRETURNS;

SELECT * FROM STAGE.MS_ADWBI.STG_FACT_RETURNS;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Queries to Load the Data to Work from Stage (Dimension Tables)

-- DIM_PRODUCT_CATEGORY

-- Sequence
CREATE OR REPLACE SEQUENCE MS_ADWBI.WORK.SEQ_DIM_PRODUCT_CATEGORY START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY (
  PRODUCT_CATEGORY_SK  NUMBER NOT NULL,
  PRODUCTCATEGORYID    NUMBER NOT NULL,
  CATEGORYNAME         STRING,

  StartDateTime        TIMESTAMP_NTZ NOT NULL,
  EndDateTime          TIMESTAMP_NTZ,
  CurrentFlag          BOOLEAN NOT NULL,
  DeleteFlag           BOOLEAN NOT NULL,

  WInsertDate          TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  WUpdateDate          TIMESTAMP_NTZ,

  CONSTRAINT UK_DIM_PRODUCT_CATEGORY UNIQUE (PRODUCTCATEGORYID)
);


SET BATCH_TS = CURRENT_TIMESTAMP();

-- Upsert (SCD1 overwrite)
MERGE INTO MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY t
USING (
  SELECT
    PRODUCTCATEGORYID,
    CATEGORYNAME
  FROM STAGE.MS_ADWBI.STG_PRODUCT_CATEGORY
) s
ON t.PRODUCTCATEGORYID = s.PRODUCTCATEGORYID

WHEN MATCHED THEN UPDATE SET
  t.CATEGORYNAME   = s.CATEGORYNAME,
  t.CurrentFlag    = TRUE,
  t.DeleteFlag     = FALSE,
  t.EndDateTime    = NULL,
  t.WUpdateDate    = $BATCH_TS

WHEN NOT MATCHED THEN INSERT (
  PRODUCT_CATEGORY_SK,
  PRODUCTCATEGORYID,
  CATEGORYNAME,
  StartDateTime,
  EndDateTime,
  CurrentFlag,
  DeleteFlag,
  WInsertDate,
  WUpdateDate
) VALUES (
  MS_ADWBI.WORK.SEQ_DIM_PRODUCT_CATEGORY.NEXTVAL,
  s.PRODUCTCATEGORYID,
  s.CATEGORYNAME,
  $BATCH_TS,
  NULL,
  TRUE,
  FALSE,
  $BATCH_TS,
  $BATCH_TS
);

-- Handle deletes (missing from stage snapshot)
UPDATE MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY t
SET
  DeleteFlag   = TRUE,
  CurrentFlag  = FALSE,
  EndDateTime  = $BATCH_TS,
  WUpdateDate  = $BATCH_TS
WHERE t.CurrentFlag = TRUE
  AND t.DeleteFlag = FALSE
  AND NOT EXISTS (
    SELECT 1
    FROM STAGE.MS_ADWBI.STG_PRODUCT_CATEGORY s
    WHERE s.PRODUCTCATEGORYID = t.PRODUCTCATEGORYID
  );

SELECT * FROM MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY;

-- DIM_PRODUCT_SUBCATEGORY

-- Sequence
CREATE OR REPLACE SEQUENCE MS_ADWBI.WORK.SEQ_DIM_PRODUCT_SUBCATEGORY START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY (
  PRODUCT_SUBCATEGORY_SK  NUMBER NOT NULL,
  PRODUCTSUBCATEGORYID    NUMBER NOT NULL,   -- business key
  PRODUCTCATEGORYID       NUMBER NOT NULL,   -- business key (lineage)
  PRODUCT_CATEGORY_SK     NUMBER NOT NULL,   -- surrogate FK to DIM_PRODUCT_CATEGORY
  SUBCATEGORYNAME         STRING,

  StartDateTime           TIMESTAMP_NTZ NOT NULL,
  EndDateTime             TIMESTAMP_NTZ,
  CurrentFlag             BOOLEAN NOT NULL,
  DeleteFlag              BOOLEAN NOT NULL,

  WInsertDate             TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  WUpdateDate             TIMESTAMP_NTZ,

  CONSTRAINT UK_DIM_PRODUCT_SUBCATEGORY UNIQUE (PRODUCTSUBCATEGORYID)
);

SET BATCH_TS = CURRENT_TIMESTAMP();

MERGE INTO MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY t
USING (
  SELECT
    s.PRODUCTSUBCATEGORYID,
    s.PRODUCTCATEGORYID,
    c.PRODUCT_CATEGORY_SK,
    s.SUBCATEGORYNAME
  FROM STAGE.MS_ADWBI.STG_PRODUCT_SUBCATEGORY s
  JOIN MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY c
    ON c.PRODUCTCATEGORYID = s.PRODUCTCATEGORYID
   AND c.CurrentFlag = TRUE
   AND c.DeleteFlag  = FALSE
) s
ON t.PRODUCTSUBCATEGORYID = s.PRODUCTSUBCATEGORYID

WHEN MATCHED THEN UPDATE SET
  t.PRODUCTCATEGORYID   = s.PRODUCTCATEGORYID,
  t.PRODUCT_CATEGORY_SK = s.PRODUCT_CATEGORY_SK,
  t.SUBCATEGORYNAME     = s.SUBCATEGORYNAME,
  t.CurrentFlag         = TRUE,
  t.DeleteFlag          = FALSE,
  t.EndDateTime         = NULL,
  t.WUpdateDate         = $BATCH_TS

WHEN NOT MATCHED THEN INSERT (
  PRODUCT_SUBCATEGORY_SK,
  PRODUCTSUBCATEGORYID,
  PRODUCTCATEGORYID,
  PRODUCT_CATEGORY_SK,
  SUBCATEGORYNAME,
  StartDateTime,
  EndDateTime,
  CurrentFlag,
  DeleteFlag,
  WInsertDate,
  WUpdateDate
) VALUES (
  MS_ADWBI.WORK.SEQ_DIM_PRODUCT_SUBCATEGORY.NEXTVAL,
  s.PRODUCTSUBCATEGORYID,
  s.PRODUCTCATEGORYID,
  s.PRODUCT_CATEGORY_SK,
  s.SUBCATEGORYNAME,
  $BATCH_TS,
  NULL,
  TRUE,
  FALSE,
  $BATCH_TS,
  $BATCH_TS
);

-- Handle deletes
UPDATE MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY t
SET
  DeleteFlag   = TRUE,
  CurrentFlag  = FALSE,
  EndDateTime  = $BATCH_TS,
  WUpdateDate  = $BATCH_TS
WHERE t.CurrentFlag = TRUE
  AND t.DeleteFlag = FALSE
  AND NOT EXISTS (
    SELECT 1
    FROM STAGE.MS_ADWBI.STG_PRODUCT_SUBCATEGORY s
    WHERE s.PRODUCTSUBCATEGORYID = t.PRODUCTSUBCATEGORYID
  );

SELECT * FROM MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY;

-- DIM_TERRITORY

-- Sequence
CREATE OR REPLACE SEQUENCE MS_ADWBI.WORK.SEQ_DIM_TERRITORY START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE MS_ADWBI.WORK.DIM_TERRITORY (
  TERRITORY_SK   NUMBER NOT NULL,
  TERRITORYID    NUMBER NOT NULL,

  Region         STRING,
  Country        STRING,
  Continent      STRING,

  StartDateTime  TIMESTAMP_NTZ NOT NULL,
  EndDateTime    TIMESTAMP_NTZ,
  CurrentFlag    BOOLEAN NOT NULL,
  DeleteFlag     BOOLEAN NOT NULL,

  WInsertDate    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  WUpdateDate    TIMESTAMP_NTZ,

  CONSTRAINT UK_DIM_TERRITORY UNIQUE (TERRITORYID)
);

SET BATCH_TS = CURRENT_TIMESTAMP();

MERGE INTO MS_ADWBI.WORK.DIM_TERRITORY t
USING (
  SELECT DISTINCT
    TerritoryID,
    Region,
    Country,
    Continent
  FROM STAGE.MS_ADWBI.STG_TERRITORY
  WHERE TerritoryID IS NOT NULL
) s
ON t.TERRITORYID = s.TerritoryID

WHEN MATCHED THEN UPDATE SET
  t.Region       = s.Region,
  t.Country      = s.Country,
  t.Continent    = s.Continent,
  t.CurrentFlag  = TRUE,
  t.DeleteFlag   = FALSE,
  t.EndDateTime  = NULL,
  t.WUpdateDate  = $BATCH_TS

WHEN NOT MATCHED THEN INSERT (
  TERRITORY_SK,
  TERRITORYID,
  Region,
  Country,
  Continent,
  StartDateTime,
  EndDateTime,
  CurrentFlag,
  DeleteFlag,
  WInsertDate,
  WUpdateDate
) VALUES (
  MS_ADWBI.WORK.SEQ_DIM_TERRITORY.NEXTVAL,
  s.TerritoryID,
  s.Region,
  s.Country,
  s.Continent,
  $BATCH_TS,
  NULL,
  TRUE,
  FALSE,
  $BATCH_TS,
  $BATCH_TS
);

-- Deletes: missing from stage snapshot
UPDATE MS_ADWBI.WORK.DIM_TERRITORY t
SET
  DeleteFlag   = TRUE,
  CurrentFlag  = FALSE,
  EndDateTime  = $BATCH_TS,
  WUpdateDate  = $BATCH_TS
WHERE t.CurrentFlag = TRUE
  AND t.DeleteFlag = FALSE
  AND NOT EXISTS (
    SELECT 1
    FROM STAGE.MS_ADWBI.STG_TERRITORY s
    WHERE s.TerritoryID = t.TERRITORYID
  );

SELECT * FROM MS_ADWBI.WORK.DIM_TERRITORY;

-- DIM_CALENDAR

CREATE OR REPLACE TABLE MS_ADWBI.WORK.DIM_CALENDAR (
  DATE_SK         NUMBER(8,0) NOT NULL,   -- MMDDYYYY
  CalendarDate    DATE NOT NULL,

  StartDateTime   TIMESTAMP_NTZ NOT NULL,
  EndDateTime     TIMESTAMP_NTZ,
  CurrentFlag     BOOLEAN NOT NULL,
  DeleteFlag      BOOLEAN NOT NULL,

  WInsertDate     TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  WUpdateDate     TIMESTAMP_NTZ,

  CONSTRAINT PK_DIM_CALENDAR PRIMARY KEY (DATE_SK)
);

SET BATCH_TS = CURRENT_TIMESTAMP();

CREATE OR REPLACE TABLE MS_ADWBI.WORK.DIM_CALENDAR AS
SELECT
  TO_NUMBER(TO_CHAR(DATE, 'MMDDYYYY')) AS DATE_SK,
  DATE                                AS CalendarDate,

  $BATCH_TS                           AS StartDateTime,
  NULL                                AS EndDateTime,
  TRUE                                AS CurrentFlag,
  FALSE                               AS DeleteFlag,

  $BATCH_TS                           AS WInsertDate,
  $BATCH_TS                           AS WUpdateDate
FROM STAGE.MS_ADWBI.STG_CALENDAR;

SELECT * FROM MS_ADWBI.WORK.DIM_CALENDAR;

--  DIM_PRODUCT

-- SEQUENCE
CREATE OR REPLACE SEQUENCE MS_ADWBI.WORK.SEQ_DIM_PRODUCT START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE MS_ADWBI.WORK.DIM_PRODUCT (
  PRODUCT_SK             NUMBER NOT NULL,
  PRODUCTID              NUMBER(38,0) NOT NULL,          -- business key

  PRODUCTMODELID         NUMBER(38,0),
  PRODUCTSUBCATEGORYID   NUMBER(38,0),                  
  PRODUCT_SUBCATEGORY_SK NUMBER(38,0),                   -- FK to DIM_PRODUCT_SUBCATEGORY
  PRODUCT_CATEGORY_SK    NUMBER(38,0),                   -- FK to DIM_PRODUCT_CATEGORY

  PRODUCTSKU             STRING,
  PRODUCTNAME            STRING,                         -- SCD1
  MODELNAME              STRING,                         -- SCD2
  PRODUCTDESCRIPTION     STRING,                         -- SCD2
  PRODUCTCOLOR           STRING,                         -- SCD1
  PRODUCTSIZE            STRING,                         -- SCD1
  PRODUCTSTYLE           STRING,                         -- SCD1
  PRODUCTCOST            NUMBER(18,2),                   -- SCD2
  PRODUCTPRICE           NUMBER(18,2),                   -- SCD2

  StartDateTime          TIMESTAMP_NTZ NOT NULL,
  EndDateTime            TIMESTAMP_NTZ,
  CurrentFlag            BOOLEAN NOT NULL,
  DeleteFlag             BOOLEAN NOT NULL,

  WInsertDate            TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  WUpdateDate            TIMESTAMP_NTZ
);

SET BATCH_TS = CURRENT_TIMESTAMP();

-- 1) Typed stage snapshot + resolve Subcategory_SK and Category_SK
CREATE OR REPLACE TEMP TABLE TMP_PRODUCT AS
SELECT
  p.PRODUCTID                                      AS PRODUCTID,
  TRY_TO_NUMBER(p.PRODUCTMODELID)                  AS PRODUCTMODELID,
  TRY_TO_NUMBER(p.PRODUCTSUBCATEGORYID)            AS PRODUCTSUBCATEGORYID,

  sc.PRODUCT_SUBCATEGORY_SK                        AS PRODUCT_SUBCATEGORY_SK,
  sc.PRODUCT_CATEGORY_SK                           AS PRODUCT_CATEGORY_SK,

  p.PRODUCTSKU                                     AS PRODUCTSKU,
  p.PRODUCTNAME                                    AS PRODUCTNAME,
  p.MODELNAME                                      AS MODELNAME,
  p.PRODUCTDESCRIPTION                             AS PRODUCTDESCRIPTION,
  p.PRODUCTCOLOR                                   AS PRODUCTCOLOR,
  p.PRODUCTSIZE                                    AS PRODUCTSIZE,
  p.PRODUCTSTYLE                                   AS PRODUCTSTYLE,

  CAST(p.PRODUCTCOST  AS NUMBER(18,2))             AS PRODUCTCOST,
  CAST(p.PRODUCTPRICE AS NUMBER(18,2))             AS PRODUCTPRICE

FROM STAGE.MS_ADWBI.STG_PRODUCT p
LEFT JOIN MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY sc
  ON sc.PRODUCTSUBCATEGORYID = TRY_TO_NUMBER(p.PRODUCTSUBCATEGORYID)
 AND sc.CurrentFlag = TRUE
 AND sc.DeleteFlag  = FALSE
WHERE p.PRODUCTID IS NOT NULL;


-- 2) Close current rows if any SCD2 field changed
-- SCD2 fields for Product: MODELNAME, PRODUCTDESCRIPTION, PRODUCTCOST, PRODUCTPRICE
UPDATE MS_ADWBI.WORK.DIM_PRODUCT d
SET
  EndDateTime = $BATCH_TS,
  CurrentFlag = FALSE,
  WUpdateDate = $BATCH_TS
FROM TMP_PRODUCT s
WHERE d.PRODUCTID = s.PRODUCTID
  AND d.CurrentFlag = TRUE
  AND d.DeleteFlag  = FALSE
  AND (
       COALESCE(d.MODELNAME,'')           <> COALESCE(s.MODELNAME,'')
    OR COALESCE(d.PRODUCTDESCRIPTION,'')  <> COALESCE(s.PRODUCTDESCRIPTION,'')
    OR COALESCE(d.PRODUCTCOST, -1)        <> COALESCE(s.PRODUCTCOST, -1)
    OR COALESCE(d.PRODUCTPRICE, -1)       <> COALESCE(s.PRODUCTPRICE, -1)
  );

-- 3) Insert new rows for:
--    a) new ProductID (no current row)
--    b) changed ProductID (we just closed current row above)
INSERT INTO MS_ADWBI.WORK.DIM_PRODUCT (
  PRODUCT_SK, PRODUCTID,
  PRODUCTMODELID, PRODUCTSUBCATEGORYID, PRODUCT_SUBCATEGORY_SK, PRODUCT_CATEGORY_SK,
  PRODUCTSKU, PRODUCTNAME, MODELNAME, PRODUCTDESCRIPTION,
  PRODUCTCOLOR, PRODUCTSIZE, PRODUCTSTYLE, PRODUCTCOST, PRODUCTPRICE,
  StartDateTime, EndDateTime, CurrentFlag, DeleteFlag,
  WInsertDate, WUpdateDate
)
SELECT
  MS_ADWBI.WORK.SEQ_DIM_PRODUCT.NEXTVAL,
  s.PRODUCTID,
  s.PRODUCTMODELID, s.PRODUCTSUBCATEGORYID, s.PRODUCT_SUBCATEGORY_SK, s.PRODUCT_CATEGORY_SK,
  s.PRODUCTSKU, s.PRODUCTNAME, s.MODELNAME, s.PRODUCTDESCRIPTION,
  s.PRODUCTCOLOR, s.PRODUCTSIZE, s.PRODUCTSTYLE, s.PRODUCTCOST, s.PRODUCTPRICE,
  $BATCH_TS, NULL, TRUE, FALSE,
  $BATCH_TS, $BATCH_TS
FROM TMP_PRODUCT s
LEFT JOIN MS_ADWBI.WORK.DIM_PRODUCT d
  ON d.PRODUCTID = s.PRODUCTID
 AND d.CurrentFlag = TRUE
WHERE d.PRODUCTID IS NULL
   OR (
       COALESCE(d.MODELNAME,'')           <> COALESCE(s.MODELNAME,'')
    OR COALESCE(d.PRODUCTDESCRIPTION,'')  <> COALESCE(s.PRODUCTDESCRIPTION,'')
    OR COALESCE(d.PRODUCTCOST, -1)        <> COALESCE(s.PRODUCTCOST, -1)
    OR COALESCE(d.PRODUCTPRICE, -1)       <> COALESCE(s.PRODUCTPRICE, -1)
   );

-- 4) SCD1 overwrite columns on the current row
-- SCD1 overwrite only when something actually changed
UPDATE MS_ADWBI.WORK.DIM_PRODUCT d
SET
  PRODUCTMODELID          = s.PRODUCTMODELID,
  PRODUCTSUBCATEGORYID    = s.PRODUCTSUBCATEGORYID,
  PRODUCT_SUBCATEGORY_SK  = s.PRODUCT_SUBCATEGORY_SK,
  PRODUCT_CATEGORY_SK     = s.PRODUCT_CATEGORY_SK,
  PRODUCTSKU              = s.PRODUCTSKU,
  PRODUCTNAME             = s.PRODUCTNAME,
  PRODUCTCOLOR            = s.PRODUCTCOLOR,
  PRODUCTSIZE             = s.PRODUCTSIZE,
  PRODUCTSTYLE            = s.PRODUCTSTYLE,
  WUpdateDate             = $BATCH_TS
FROM TMP_PRODUCT s
WHERE d.PRODUCTID = s.PRODUCTID
  AND d.CurrentFlag = TRUE
  AND d.DeleteFlag  = FALSE
  AND (
       d.PRODUCTMODELID         IS DISTINCT FROM s.PRODUCTMODELID
    OR d.PRODUCTSUBCATEGORYID   IS DISTINCT FROM s.PRODUCTSUBCATEGORYID
    OR d.PRODUCT_SUBCATEGORY_SK IS DISTINCT FROM s.PRODUCT_SUBCATEGORY_SK
    OR d.PRODUCT_CATEGORY_SK    IS DISTINCT FROM s.PRODUCT_CATEGORY_SK
    OR d.PRODUCTSKU             IS DISTINCT FROM s.PRODUCTSKU
    OR d.PRODUCTNAME            IS DISTINCT FROM s.PRODUCTNAME
    OR d.PRODUCTCOLOR           IS DISTINCT FROM s.PRODUCTCOLOR
    OR d.PRODUCTSIZE            IS DISTINCT FROM s.PRODUCTSIZE
    OR d.PRODUCTSTYLE           IS DISTINCT FROM s.PRODUCTSTYLE
  );


-- 5) Deletes: mark as deleted if ProductID disappears from stage snapshot
UPDATE MS_ADWBI.WORK.DIM_PRODUCT d
SET
  DeleteFlag  = TRUE,
  CurrentFlag = FALSE,
  EndDateTime = $BATCH_TS,
  WUpdateDate = $BATCH_TS
WHERE d.CurrentFlag = TRUE
  AND d.DeleteFlag  = FALSE
  AND NOT EXISTS (
    SELECT 1
    FROM TMP_PRODUCT s
    WHERE s.PRODUCTID = d.PRODUCTID
  );

SELECT * FROM MS_ADWBI.WORK.DIM_PRODUCT;


-- DIM_CUSTOMER

CREATE OR REPLACE SEQUENCE MS_ADWBI.WORK.SEQ_DIM_CUSTOMER START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE MS_ADWBI.WORK.DIM_CUSTOMER (
  CUSTOMER_SK       NUMBER NOT NULL,
  BUSINESSENTITYID  NUMBER(38,0) NOT NULL,     -- business key

  PREFIX            STRING,                    -- SCD1
  FIRSTNAME         STRING,                    -- SCD1
  LASTNAME          STRING,                    -- SCD1
  BIRTHDATE         DATE,                      -- SCD1 
  MARITALSTATUS     STRING,                    -- SCD2
  GENDER            STRING,                    -- SCD1
  EMAILADDRESS      STRING,                    -- SCD1
  ANNUALINCOME      NUMBER(18,2),              -- SCD2
  TOTALCHILDREN     NUMBER(10,0),              -- SCD2
  EDUCATIONLEVEL    STRING,                    -- SCD2
  OCCUPATION        STRING,                    -- SCD2
  HOMEOWNER         STRING,                    -- SCD2

  StartDateTime     TIMESTAMP_NTZ NOT NULL,
  EndDateTime       TIMESTAMP_NTZ,
  CurrentFlag       BOOLEAN NOT NULL,
  DeleteFlag        BOOLEAN NOT NULL,

  WInsertDate       TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  WUpdateDate       TIMESTAMP_NTZ
);

SET BATCH_TS = CURRENT_TIMESTAMP();

-- 1) Typed stage snapshot
CREATE OR REPLACE TEMP TABLE TMP_CUSTOMER AS
SELECT
  BUSINESSENTITYID                          AS BUSINESSENTITYID,
  PREFIX                                   AS PREFIX,
  FIRSTNAME                                AS FIRSTNAME,
  LASTNAME                                 AS LASTNAME,
  TRY_TO_DATE(BIRTHDATE)                   AS BIRTHDATE,
  MARITALSTATUS                            AS MARITALSTATUS,
  GENDER                                   AS GENDER,
  EMAILADDRESS                             AS EMAILADDRESS,
  TRY_TO_DECIMAL(ANNUALINCOME, 18, 2)      AS ANNUALINCOME,
  TRY_TO_NUMBER(TOTALCHILDREN)             AS TOTALCHILDREN,
  EDUCATIONLEVEL                           AS EDUCATIONLEVEL,
  OCCUPATION                               AS OCCUPATION,
  HOMEOWNER                                AS HOMEOWNER
FROM STAGE.MS_ADWBI.STG_CUSTOMER
WHERE BUSINESSENTITYID IS NOT NULL;

-- 2) Close current rows if any SCD2 field changed
-- SCD2 fields for Customer: MaritalStatus, AnnualIncome, TotalChildren, EducationLevel, Occupation, HomeOwner
UPDATE MS_ADWBI.WORK.DIM_CUSTOMER d
SET
  EndDateTime = $BATCH_TS,
  CurrentFlag = FALSE,
  WUpdateDate = $BATCH_TS
FROM TMP_CUSTOMER s
WHERE d.BUSINESSENTITYID = s.BUSINESSENTITYID
  AND d.CurrentFlag = TRUE
  AND d.DeleteFlag  = FALSE
  AND (
       COALESCE(d.MARITALSTATUS,'')   <> COALESCE(s.MARITALSTATUS,'')
    OR COALESCE(d.ANNUALINCOME, -1)   <> COALESCE(s.ANNUALINCOME, -1)
    OR COALESCE(d.TOTALCHILDREN, -1)  <> COALESCE(s.TOTALCHILDREN, -1)
    OR COALESCE(d.EDUCATIONLEVEL,'')  <> COALESCE(s.EDUCATIONLEVEL,'')
    OR COALESCE(d.OCCUPATION,'')      <> COALESCE(s.OCCUPATION,'')
    OR COALESCE(d.HOMEOWNER,'')       <> COALESCE(s.HOMEOWNER,'')
  );

-- 3) Insert new rows for new or changed customers
INSERT INTO MS_ADWBI.WORK.DIM_CUSTOMER (
  CUSTOMER_SK, 
  BUSINESSENTITYID,
  PREFIX, FIRSTNAME, LASTNAME, BIRTHDATE, MARITALSTATUS, GENDER, EMAILADDRESS,
  ANNUALINCOME, TOTALCHILDREN, EDUCATIONLEVEL, OCCUPATION, HOMEOWNER,
  StartDateTime, EndDateTime, CurrentFlag, DeleteFlag,
  WInsertDate, WUpdateDate
)
SELECT
  MS_ADWBI.WORK.SEQ_DIM_CUSTOMER.NEXTVAL,
  s.BUSINESSENTITYID,
  s.PREFIX, s.FIRSTNAME, s.LASTNAME, s.BIRTHDATE, s.MARITALSTATUS, s.GENDER, s.EMAILADDRESS,
  s.ANNUALINCOME, s.TOTALCHILDREN, s.EDUCATIONLEVEL, s.OCCUPATION, s.HOMEOWNER,
  $BATCH_TS, NULL, TRUE, FALSE,
  $BATCH_TS, $BATCH_TS
FROM TMP_CUSTOMER s
LEFT JOIN MS_ADWBI.WORK.DIM_CUSTOMER d
  ON d.BUSINESSENTITYID = s.BUSINESSENTITYID
 AND d.CurrentFlag = TRUE
WHERE d.BUSINESSENTITYID IS NULL
   OR (
       COALESCE(d.MARITALSTATUS,'')   <> COALESCE(s.MARITALSTATUS,'')
    OR COALESCE(d.ANNUALINCOME, -1)   <> COALESCE(s.ANNUALINCOME, -1)
    OR COALESCE(d.TOTALCHILDREN, -1)  <> COALESCE(s.TOTALCHILDREN, -1)
    OR COALESCE(d.EDUCATIONLEVEL,'')  <> COALESCE(s.EDUCATIONLEVEL,'')
    OR COALESCE(d.OCCUPATION,'')      <> COALESCE(s.OCCUPATION,'')
    OR COALESCE(d.HOMEOWNER,'')       <> COALESCE(s.HOMEOWNER,'')
   );

-- 4) SCD1 overwrite fields on the current row (includes Gender rule)
UPDATE MS_ADWBI.WORK.DIM_CUSTOMER d
SET
  PREFIX       = s.PREFIX,
  FIRSTNAME    = s.FIRSTNAME,
  LASTNAME     = s.LASTNAME,
  BIRTHDATE    = s.BIRTHDATE,
  GENDER       = s.GENDER,
  EMAILADDRESS = s.EMAILADDRESS,
  WUpdateDate  = $BATCH_TS
FROM TMP_CUSTOMER s
WHERE d.BUSINESSENTITYID = s.BUSINESSENTITYID
  AND d.CurrentFlag = TRUE
  AND d.DeleteFlag  = FALSE
  AND (
       d.PREFIX       IS DISTINCT FROM s.PREFIX
    OR d.FIRSTNAME    IS DISTINCT FROM s.FIRSTNAME
    OR d.LASTNAME     IS DISTINCT FROM s.LASTNAME
    OR d.BIRTHDATE    IS DISTINCT FROM s.BIRTHDATE
    OR d.GENDER       IS DISTINCT FROM s.GENDER
    OR d.EMAILADDRESS IS DISTINCT FROM s.EMAILADDRESS
  );


-- 5) Deletes: mark deleted if customer disappears from stage
UPDATE MS_ADWBI.WORK.DIM_CUSTOMER d
SET
  DeleteFlag  = TRUE,
  CurrentFlag = FALSE,
  EndDateTime = $BATCH_TS,
  WUpdateDate = $BATCH_TS
WHERE d.CurrentFlag = TRUE
  AND d.DeleteFlag  = FALSE
  AND NOT EXISTS (
    SELECT 1
    FROM TMP_CUSTOMER s
    WHERE s.BUSINESSENTITYID = d.BUSINESSENTITYID
  );

SELECT * FROM MS_ADWBI.WORK.DIM_CUSTOMER;

-- FACT_SALES

CREATE OR REPLACE TABLE MS_ADWBI.WORK.FACT_SALES (
  OrderDate_SK    NUMBER(8,0),
  StockDate_SK    NUMBER(8,0),

  OrderNumber     STRING,
  OrderLineItem   NUMBER(38,0),

  PRODUCT_SK      NUMBER,
  CUSTOMER_SK     NUMBER,
  TERRITORY_SK    NUMBER,

  OrderQuantity   NUMBER(38,0),

  WInsertDate     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  WUpdateDate     TIMESTAMP_NTZ
);

INSERT INTO MS_ADWBI.WORK.FACT_SALES (
  OrderDate_SK, StockDate_SK,
  OrderNumber, OrderLineItem,
  PRODUCT_SK, CUSTOMER_SK, TERRITORY_SK,
  OrderQuantity,
  WInsertDate, WUpdateDate
)
SELECT
  cal_o.DATE_SK AS OrderDate_SK,
  cal_s.DATE_SK AS StockDate_SK,

  s.ORDERNUMBER,
  s.ORDERLINEITEM,

  p.PRODUCT_SK,
  c.CUSTOMER_SK,
  t.TERRITORY_SK,

  s.ORDERQUANTITY,

  CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM STAGE.MS_ADWBI.STG_FACT_SALES s

LEFT JOIN MS_ADWBI.WORK.DIM_CALENDAR cal_o
  ON cal_o.CalendarDate = s.ORDERDATE
 AND cal_o.CurrentFlag = TRUE AND cal_o.DeleteFlag = FALSE

LEFT JOIN MS_ADWBI.WORK.DIM_CALENDAR cal_s
  ON cal_s.CalendarDate = s.STOCKDATE
 AND cal_s.CurrentFlag = TRUE AND cal_s.DeleteFlag = FALSE

LEFT JOIN MS_ADWBI.WORK.DIM_PRODUCT p
  ON p.PRODUCTID = s.PRODUCTID
 AND p.CurrentFlag = TRUE AND p.DeleteFlag = FALSE

LEFT JOIN MS_ADWBI.WORK.DIM_CUSTOMER c
  ON c.BUSINESSENTITYID = s.BUSINESSENTITYID
 AND c.CurrentFlag = TRUE AND c.DeleteFlag = FALSE

LEFT JOIN MS_ADWBI.WORK.DIM_TERRITORY t
  ON t.TERRITORYID = s.TERRITORYID
 AND t.CurrentFlag = TRUE AND t.DeleteFlag = FALSE;


SELECT * FROM MS_ADWBI.WORK.FACT_SALES;

-- FACT_RETURNS

CREATE OR REPLACE TABLE MS_ADWBI.WORK.FACT_RETURNS (
  ReturnDate_SK   NUMBER(8,0),

  TERRITORY_SK    NUMBER,
  PRODUCT_SK      NUMBER,

  ReturnQuantity  NUMBER(38,0),

  WInsertDate     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  WUpdateDate     TIMESTAMP_NTZ
);

INSERT INTO MS_ADWBI.WORK.FACT_RETURNS (
  ReturnDate_SK,
  TERRITORY_SK,
  PRODUCT_SK,
  ReturnQuantity,
  WInsertDate, WUpdateDate
)
SELECT
  cal.DATE_SK AS ReturnDate_SK,
  t.TERRITORY_SK,
  p.PRODUCT_SK,
  r.RETURNQUANTITY,

  CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
FROM STAGE.MS_ADWBI.STG_FACT_RETURNS r

LEFT JOIN MS_ADWBI.WORK.DIM_CALENDAR cal
  ON cal.CalendarDate = r.RETURNDATE
 AND cal.CurrentFlag = TRUE AND cal.DeleteFlag = FALSE

LEFT JOIN MS_ADWBI.WORK.DIM_TERRITORY t
  ON t.TERRITORYID = r.TERRITORYID
 AND t.CurrentFlag = TRUE AND t.DeleteFlag = FALSE

LEFT JOIN MS_ADWBI.WORK.DIM_PRODUCT p
  ON p.PRODUCTID = r.PRODUCTID
 AND p.CurrentFlag = TRUE AND p.DeleteFlag = FALSE;


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Creating Views in DATA_ACCESS From MS_ADWBI for access to build Dashboard in Power BI


CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_CALENDAR AS
SELECT 
DATE_SK,
CALENDARDATE
FROM MS_ADWBI.WORK.DIM_CALENDAR;


CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_CUSTOMER AS
SELECT 
CUSTOMER_SK,
PREFIX,
FIRSTNAME,
LASTNAME,
BIRTHDATE,
MARITALSTATUS,
GENDER,
EMAILADDRESS,
ANNUALINCOME,
TOTALCHILDREN,
EDUCATIONLEVEL,
OCCUPATION,
HOMEOWNER
FROM MS_ADWBI.WORK.DIM_CUSTOMER;


CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_PRODUCT AS
SELECT 
PRODUCT_SK,
PRODUCT_SUBCATEGORY_SK,
PRODUCTSKU,
PRODUCTNAME,
MODELNAME,
PRODUCTDESCRIPTION,
PRODUCTCOLOR,
PRODUCTSIZE,
PRODUCTSTYLE,
PRODUCTCOST,
PRODUCTPRICE
FROM MS_ADWBI.WORK.DIM_PRODUCT;


CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_PRODUCT_CATEGORY AS
SELECT 
    PRODUCT_CATEGORY_SK,
    CATEGORYNAME
FROM MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY;


CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_PRODUCT_SUBCATEGORY AS
SELECT 
    PRODUCT_SUBCATEGORY_SK,
    PRODUCT_CATEGORY_SK,
    SUBCATEGORYNAME
FROM MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY;


CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_TERRITORY AS
SELECT 
    TERRITORY_SK,
    REGION,
    COUNTRY,
    CONTINENT
FROM MS_ADWBI.WORK.DIM_TERRITORY;


CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.FACT_SALES AS
SELECT 
    ORDERDATE_SK,
    STOCKDATE_SK,
    ORDERNUMBER,
    ORDERLINEITEM,
    PRODUCT_SK,
    CUSTOMER_SK,
    TERRITORY_SK,
    ORDERQUANTITY
FROM MS_ADWBI.WORK.FACT_SALES;


CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.FACT_RETURNS AS
SELECT 
    RETURNDATE_SK,
    TERRITORY_SK,
    PRODUCT_SK,
    RETURNQUANTITY
FROM MS_ADWBI.WORK.FACT_RETURNS;


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


-- CREATE OR REPLACE PROCEDURE DATA_ACCESS.PUBLIC.CREATE_DATA_ACCESS_VIEWS_FROM_MS_ADWBI()
-- RETURNS STRING
-- LANGUAGE JAVASCRIPT
-- EXECUTE AS CALLER
-- AS
-- $$
-- var SRC_DB = "MS_ADWBI";
-- var SRC_SCHEMA = "WORK";
-- var TGT_DB = "DATA_ACCESS";
-- var TGT_SCHEMA = "MS_ADWBI";

-- // columns to exclude if present (case-insensitive match)
-- var AUDIT_COLS = new Set([
--   "STARTDATETIME",
--   "ENDDATETIME",
--   "CURRENTFLAG",
--   "DELETEFLAG",
--   "WINSERTDATE",
--   "WUPDATEDATE"
-- ]);

-- // list all base tables in WORK schema
-- var listSql = `
--   SELECT TABLE_NAME
--   FROM ${SRC_DB}.INFORMATION_SCHEMA.TABLES
--   WHERE TABLE_SCHEMA = '${SRC_SCHEMA}'
--     AND TABLE_TYPE = 'BASE TABLE'
--   ORDER BY TABLE_NAME
-- `;

-- var rs = snowflake.createStatement({sqlText: listSql}).execute();
-- var viewCount = 0;

-- while (rs.next()) {
--   var tbl = rs.getColumnValue(1);

--   // get columns for table
--   var colSql = `
--     SELECT COLUMN_NAME
--     FROM ${SRC_DB}.INFORMATION_SCHEMA.COLUMNS
--     WHERE TABLE_SCHEMA = '${SRC_SCHEMA}'
--       AND TABLE_NAME = '${tbl}'
--     ORDER BY ORDINAL_POSITION
--   `;
--   var crs = snowflake.createStatement({sqlText: colSql}).execute();

--   var cols = [];
--   var currentFlagCol = null; // exact column name if exists
--   var deleteFlagCol  = null; // exact column name if exists

--   while (crs.next()) {
--     var col = crs.getColumnValue(1);
--     var colU = (col + "").toUpperCase();

--     // detect flag column names (store exact)
--     if (colU === "CURRENTFLAG") currentFlagCol = col;
--     if (colU === "DELETEFLAG")  deleteFlagCol  = col;

--     // include column only if it's not in the audit list
--     if (!AUDIT_COLS.has(colU)) {
--       cols.push(`"${col}"`);
--     }
--   }

--   // if table only had audit cols, skip view creation
--   if (cols.length === 0) {
--     continue;
--   }

--   // apply filter ONLY when those columns exist (works for dims; facts won't have them)
--   var whereClause = "";
--   if (currentFlagCol && deleteFlagCol) {
--     whereClause = ` WHERE "${currentFlagCol}" = TRUE AND "${deleteFlagCol}" = FALSE`;
--   }

--   var createViewSql = `
--     CREATE OR REPLACE VIEW ${TGT_DB}."${TGT_SCHEMA}"."${tbl}" AS
--     SELECT ${cols.join(", ")}
--     FROM ${SRC_DB}."${SRC_SCHEMA}"."${tbl}"${whereClause}
--   `;

--   snowflake.createStatement({sqlText: createViewSql}).execute();
--   viewCount++;
-- }

-- return `Created/Replaced ${viewCount} views in ${TGT_DB}.${TGT_SCHEMA} from ${SRC_DB}.${SRC_SCHEMA} (audit columns removed if present).`;
-- $$;

-- CALL DATA_ACCESS.PUBLIC.CREATE_DATA_ACCESS_VIEWS_FROM_MS_ADWBI();

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


SELECT * FROM DATA_ACCESS.MS_ADWBI.FACT_SALES;

SELECT * FROM DATA_ACCESS.MS_ADWBI.FACT_RETURNS;



SELECT * FROM STAGE.MS_ADWBI.STG_CUSTOMER;
SELECT * FROM MS_ADWBI.WORK.DIM_CUSTOMER;


SELECT * FROM DATA_ACCESS.MS_ADWBI.DIM_CUSTOMER;


TRUNCATE TABLE  MS_ADWBI.WORK.DIM_CUSTOMER;



SELECT * FROM DATA_ACCESS.MS_SALES.V_UDEMYSALES;
SELECT * FROM STAGE.MS_ADWBI.STG_FACT_SALES;


 
