TRUNCATE TABLE MS_ADWBI.CTRL.ADWBI_EXECUTE_PROCEDURES_MASTER_TABLE;

INSERT INTO MS_ADWBI.CTRL.ADWBI_EXECUTE_PROCEDURES_MASTER_TABLE
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_01' JOB_CODE,
    'REFRESH_CUSTOMER_TABLE' JOB_NAME,
    1 STEP_NUMBER,
    'Truncate Table STG_CUSTOMER' STEP_DESC,
    $$TRUNCATE TABLE STAGE.MS_ADWBI.STG_CUSTOMER;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_CUSTOMER' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_CUSTOMER' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_01' JOB_CODE,
    'REFRESH_CUSTOMER_TABLE' JOB_NAME,
    2 STEP_NUMBER,
    'Insert Data to STG_CUSTOMER table from DATA_ACCESS Database' STEP_DESC,
    $$INSERT INTO STAGE.MS_ADWBI.STG_CUSTOMER
    SELECT
      p.BUSINESSENTITYID   AS BusinessEntityID,
      p.TITLE              AS Prefix,
      p.FIRSTNAME          AS FirstName,
      p.LASTNAME           AS LastName,
      d.BIRTHDATE          AS BirthDate,
      d.MARITALSTATUS      AS MaritalStatus,
      d.GENDER             AS Gender,
      e.EMAILADDRESS       AS EmailAddress,
      d.YEARLYINCOME       AS AnnualIncome,
      d.TOTALCHILDREN      AS TotalChildren,
      d.ENGLISHEDUCATION   AS EducationLevel,
      d.ENGLISHOCCUPATION  AS Occupation,
      d.HOUSEOWNERFLAG     AS HomeOwner
    FROM DATA_ACCESS.MS_PERSON.V_PERSON p
    LEFT JOIN DATA_ACCESS.MS_PERSON.V_EMAILADDRESS e
      ON e.BUSINESSENTITYID = p.BUSINESSENTITYID
    LEFT JOIN DATA_ACCESS.MS_PERSON.V_DEMOGRAPHICS d
      ON d.BUSINESSENTITYID = p.BUSINESSENTITYID;$$ AS ETL_LOGIC,
    'DATA_ACCESS' SOURCE_DATABASE_NAME,
    'MS_PERSON' SOURCE_SCHEMA_NAME,
    'V_PERSON | V_EMAILADDRESS | V_DEMOGRAPHICS' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_CUSTOMER' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_01' JOB_CODE,
    'REFRESH_CUSTOMER_TABLE' JOB_NAME,
    3 STEP_NUMBER,
    'Insert Data to DIM_CUSTOMER table from STG_CUSTOMER Table using SCD2' STEP_DESC,
    $$SET BATCH_TS = CURRENT_TIMESTAMP();

    -- 1) Typed stage snapshot
    CREATE OR REPLACE TEMP TABLE MS_ADWBI.WORK.TMP_CUSTOMER AS
    SELECT
      BUSINESSENTITYID                          AS BUSINESSENTITYID,
      PREFIX                                   AS PREFIX,
      FIRSTNAME                                AS FIRSTNAME,
      LASTNAME                                 AS LASTNAME,
      TRY_TO_DATE(BIRTHDATE)                   AS BIRTHDATE,
      MARITALSTATUS                            AS MARITALSTATUS,
      GENDER                                   AS GENDER,
      EMAILADDRESS                             AS EMAILADDRESS,
      TRY_TO_DECIMAL(ANNUALINCOME, 18, 2)      AS ANNUALINCOME,
      TRY_TO_NUMBER(TOTALCHILDREN)             AS TOTALCHILDREN,
      EDUCATIONLEVEL                           AS EDUCATIONLEVEL,
      OCCUPATION                               AS OCCUPATION,
      HOMEOWNER                                AS HOMEOWNER
    FROM STAGE.MS_ADWBI.STG_CUSTOMER
    WHERE BUSINESSENTITYID IS NOT NULL;
    
    -- 2) Close current rows if any SCD2 field changed
    UPDATE MS_ADWBI.WORK.DIM_CUSTOMER d
    SET
      EndDateTime = $BATCH_TS,
      CurrentFlag = FALSE,
      WUpdateDate = $BATCH_TS
    FROM MS_ADWBI.WORK.TMP_CUSTOMER s
    WHERE d.BUSINESSENTITYID = s.BUSINESSENTITYID
      AND d.CurrentFlag = TRUE
      AND d.DeleteFlag  = FALSE
      AND (
           COALESCE(d.MARITALSTATUS,'')   <> COALESCE(s.MARITALSTATUS,'')
        OR COALESCE(d.ANNUALINCOME, -1)   <> COALESCE(s.ANNUALINCOME, -1)
        OR COALESCE(d.TOTALCHILDREN, -1)  <> COALESCE(s.TOTALCHILDREN, -1)
        OR COALESCE(d.EDUCATIONLEVEL,'')  <> COALESCE(s.EDUCATIONLEVEL,'')
        OR COALESCE(d.OCCUPATION,'')      <> COALESCE(s.OCCUPATION,'')
        OR COALESCE(d.HOMEOWNER,'')       <> COALESCE(s.HOMEOWNER,'')
      );
    
    -- 3) Insert new rows for new or changed customers
    INSERT INTO MS_ADWBI.WORK.DIM_CUSTOMER (
      CUSTOMER_SK, 
      BUSINESSENTITYID,
      PREFIX, FIRSTNAME, LASTNAME, BIRTHDATE, MARITALSTATUS, GENDER, EMAILADDRESS,
      ANNUALINCOME, TOTALCHILDREN, EDUCATIONLEVEL, OCCUPATION, HOMEOWNER,
      StartDateTime, EndDateTime, CurrentFlag, DeleteFlag,
      WInsertDate, WUpdateDate
    )
    SELECT
      MS_ADWBI.WORK.SEQ_DIM_CUSTOMER.NEXTVAL,
      s.BUSINESSENTITYID,
      s.PREFIX, s.FIRSTNAME, s.LASTNAME, s.BIRTHDATE, s.MARITALSTATUS, s.GENDER, s.EMAILADDRESS,
      s.ANNUALINCOME, s.TOTALCHILDREN, s.EDUCATIONLEVEL, s.OCCUPATION, s.HOMEOWNER,
      $BATCH_TS, NULL, TRUE, FALSE,
      $BATCH_TS, $BATCH_TS
    FROM MS_ADWBI.WORK.TMP_CUSTOMER s
    LEFT JOIN MS_ADWBI.WORK.DIM_CUSTOMER d
      ON d.BUSINESSENTITYID = s.BUSINESSENTITYID
     AND d.CurrentFlag = TRUE
    WHERE d.BUSINESSENTITYID IS NULL
       OR (
           COALESCE(d.MARITALSTATUS,'')   <> COALESCE(s.MARITALSTATUS,'')
        OR COALESCE(d.ANNUALINCOME, -1)   <> COALESCE(s.ANNUALINCOME, -1)
        OR COALESCE(d.TOTALCHILDREN, -1)  <> COALESCE(s.TOTALCHILDREN, -1)
        OR COALESCE(d.EDUCATIONLEVEL,'')  <> COALESCE(s.EDUCATIONLEVEL,'')
        OR COALESCE(d.OCCUPATION,'')      <> COALESCE(s.OCCUPATION,'')
        OR COALESCE(d.HOMEOWNER,'')       <> COALESCE(s.HOMEOWNER,'')
       );
    
    -- 4) SCD1 overwrite fields on the current row
    UPDATE MS_ADWBI.WORK.DIM_CUSTOMER d
    SET
      PREFIX       = s.PREFIX,
      FIRSTNAME    = s.FIRSTNAME,
      LASTNAME     = s.LASTNAME,
      BIRTHDATE    = s.BIRTHDATE,
      GENDER       = s.GENDER,
      EMAILADDRESS = s.EMAILADDRESS,
      WUpdateDate  = $BATCH_TS
    FROM MS_ADWBI.WORK.TMP_CUSTOMER s
    WHERE d.BUSINESSENTITYID = s.BUSINESSENTITYID
      AND d.CurrentFlag = TRUE
      AND d.DeleteFlag  = FALSE
      AND (
           d.PREFIX       IS DISTINCT FROM s.PREFIX
        OR d.FIRSTNAME    IS DISTINCT FROM s.FIRSTNAME
        OR d.LASTNAME     IS DISTINCT FROM s.LASTNAME
        OR d.BIRTHDATE    IS DISTINCT FROM s.BIRTHDATE
        OR d.GENDER       IS DISTINCT FROM s.GENDER
        OR d.EMAILADDRESS IS DISTINCT FROM s.EMAILADDRESS
      );
    
    -- 5) Deletes: mark deleted if customer disappears from stage
    UPDATE MS_ADWBI.WORK.DIM_CUSTOMER d
    SET
      DeleteFlag  = TRUE,
      CurrentFlag = FALSE,
      EndDateTime = $BATCH_TS,
      WUpdateDate = $BATCH_TS
    WHERE d.CurrentFlag = TRUE
      AND d.DeleteFlag  = FALSE
      AND NOT EXISTS (
        SELECT 1
        FROM MS_ADWBI.WORK.TMP_CUSTOMER s
        WHERE s.BUSINESSENTITYID = d.BUSINESSENTITYID
    );$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_CUSTOMER' SOURCE_TABLE_NAME,
    'MS_ADWBI' TARGET_DATABASE_NAME, 
    'WORK' TARGET_SCHEMA_NAME, 
    'DIM_CUSTOMER' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_01' JOB_CODE,
    'REFRESH_CUSTOMER_TABLE' JOB_NAME,
    4 STEP_NUMBER,
    'Create View for DIM_CUSTOMER' STEP_DESC,
    $$CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_CUSTOMER AS
    SELECT 
        CUSTOMER_SK,
        PREFIX,
        FIRSTNAME,
        LASTNAME,
        BIRTHDATE,
        MARITALSTATUS,
        GENDER,
        EMAILADDRESS,
        ANNUALINCOME,
        TOTALCHILDREN,
        EDUCATIONLEVEL,
        OCCUPATION,
        HOMEOWNER
    FROM MS_ADWBI.WORK.DIM_CUSTOMER;$$ AS ETL_LOGIC,
    'MS_ADWBI' SOURCE_DATABASE_NAME,
    'WORK' SOURCE_SCHEMA_NAME,
    'DIM_CUSTOMER' SOURCE_TABLE_NAME,
    'DATA_ACCESS' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'DIM_CUSTOMER' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION

SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_02' JOB_CODE,
    'REFRESH_PRODUCT_TABLE' JOB_NAME,
    1 STEP_NUMBER,
    'Truncate Table STG_PRODUCT' STEP_DESC,
    $$TRUNCATE STAGE.MS_ADWBI.STG_PRODUCT;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_PRODUCT' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_PRODUCT' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_02' JOB_CODE,
    'REFRESH_PRODUCT_TABLE' JOB_NAME,
    2 STEP_NUMBER,
    'Insert Data to STG_PRODUCT table from DATA_ACCESS Database' STEP_DESC,
    $$INSERT INTO STAGE.MS_ADWBI.STG_PRODUCT
    SELECT
      p.PRODUCTID      AS ProductID,
      p.PRODUCTMODELID AS ProductModelID,
      p.PRODUCTSUBCATEGORYID AS PRODUCTSUBCATEGORYID,
      p.PRODUCTNUMBER  AS ProductSKU,
      p.NAME           AS ProductName,
      pm.NAME          AS ModelName,
      pd.DESCRIPTION   AS ProductDescription,
      p.COLOR          AS ProductColor,
      p.SIZE           AS ProductSize,
      p.STYLE          AS ProductStyle,
      p.STANDARDCOST   AS ProductCost,
      p.LISTPRICE      AS ProductPrice
    FROM DATA_ACCESS.MS_PRODUCTION.V_PRODUCT p
    LEFT JOIN DATA_ACCESS.MS_PRODUCTION.V_PRODUCTMODEL pm
      ON pm.PRODUCTMODELID = p.PRODUCTMODELID
    LEFT JOIN DATA_ACCESS.MS_PRODUCTION.V_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE pmpd
      ON pmpd.PRODUCTMODELID = p.PRODUCTMODELID
    LEFT JOIN DATA_ACCESS.MS_PRODUCTION.V_PRODUCTDESCRIPTION pd
      ON pd.PRODUCTDESCRIPTIONID = pmpd.PRODUCTDESCRIPTIONID
    WHERE pd.PRODUCTDESCRIPTIONID < 1218;$$ AS ETL_LOGIC,
    'DATA_ACCESS' SOURCE_DATABASE_NAME,
    'MS_PRODUCTION' SOURCE_SCHEMA_NAME,
    'V_PRODUCT | V_PRODUCTMODEL | V_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE | V_PRODUCTDESCRIPTION' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_PRODUCT' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_02' JOB_CODE,
    'REFRESH_PRODUCT_TABLE' JOB_NAME,
    3 STEP_NUMBER,
    'Insert Data to DIM_PRODUCT table from STG_PRODUCT Table using SCD2' STEP_DESC,
    $$-- DIM_PRODUCT SCD2 load from STG_PRODUCT
    SET BATCH_TS = CURRENT_TIMESTAMP();
    
    CREATE OR REPLACE TEMP TABLE MS_ADWBI.WORK.TMP_PRODUCT AS
    SELECT
      p.PRODUCTID                                      AS PRODUCTID,
      TRY_TO_NUMBER(p.PRODUCTMODELID)                  AS PRODUCTMODELID,
      TRY_TO_NUMBER(p.PRODUCTSUBCATEGORYID)            AS PRODUCTSUBCATEGORYID,
    
      sc.PRODUCT_SUBCATEGORY_SK                        AS PRODUCT_SUBCATEGORY_SK,
      sc.PRODUCT_CATEGORY_SK                           AS PRODUCT_CATEGORY_SK,
    
      p.PRODUCTSKU                                     AS PRODUCTSKU,
      p.PRODUCTNAME                                    AS PRODUCTNAME,
      p.MODELNAME                                      AS MODELNAME,
      p.PRODUCTDESCRIPTION                             AS PRODUCTDESCRIPTION,
      p.PRODUCTCOLOR                                   AS PRODUCTCOLOR,
      p.PRODUCTSIZE                                    AS PRODUCTSIZE,
      p.PRODUCTSTYLE                                   AS PRODUCTSTYLE,
      CAST(p.PRODUCTCOST  AS NUMBER(18,2))             AS PRODUCTCOST,
      CAST(p.PRODUCTPRICE AS NUMBER(18,2))             AS PRODUCTPRICE
    FROM STAGE.MS_ADWBI.STG_PRODUCT p
    LEFT JOIN MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY sc
      ON sc.PRODUCTSUBCATEGORYID = TRY_TO_NUMBER(p.PRODUCTSUBCATEGORYID)
     AND sc.CurrentFlag = TRUE
     AND sc.DeleteFlag  = FALSE
    WHERE p.PRODUCTID IS NOT NULL;
    
    -- Close current rows if any SCD2 field changed
    UPDATE MS_ADWBI.WORK.DIM_PRODUCT d
    SET
      EndDateTime = $BATCH_TS,
      CurrentFlag = FALSE,
      WUpdateDate = $BATCH_TS
    FROM MS_ADWBI.WORK.TMP_PRODUCT s
    WHERE d.PRODUCTID = s.PRODUCTID
      AND d.CurrentFlag = TRUE
      AND d.DeleteFlag  = FALSE
      AND (
           COALESCE(d.MODELNAME,'')           <> COALESCE(s.MODELNAME,'')
        OR COALESCE(d.PRODUCTDESCRIPTION,'')  <> COALESCE(s.PRODUCTDESCRIPTION,'')
        OR COALESCE(d.PRODUCTCOST, -1)        <> COALESCE(s.PRODUCTCOST, -1)
        OR COALESCE(d.PRODUCTPRICE, -1)       <> COALESCE(s.PRODUCTPRICE, -1)
      );
    
    -- Insert new row for new products OR changed products (after closing)
    INSERT INTO MS_ADWBI.WORK.DIM_PRODUCT (
      PRODUCT_SK, PRODUCTID,
      PRODUCTMODELID, PRODUCTSUBCATEGORYID, PRODUCT_SUBCATEGORY_SK, PRODUCT_CATEGORY_SK,
      PRODUCTSKU, PRODUCTNAME, MODELNAME, PRODUCTDESCRIPTION,
      PRODUCTCOLOR, PRODUCTSIZE, PRODUCTSTYLE, PRODUCTCOST, PRODUCTPRICE,
      StartDateTime, EndDateTime, CurrentFlag, DeleteFlag,
      WInsertDate, WUpdateDate
    )
    SELECT
      MS_ADWBI.WORK.SEQ_DIM_PRODUCT.NEXTVAL,
      s.PRODUCTID,
      s.PRODUCTMODELID, s.PRODUCTSUBCATEGORYID, s.PRODUCT_SUBCATEGORY_SK, s.PRODUCT_CATEGORY_SK,
      s.PRODUCTSKU, s.PRODUCTNAME, s.MODELNAME, s.PRODUCTDESCRIPTION,
      s.PRODUCTCOLOR, s.PRODUCTSIZE, s.PRODUCTSTYLE, s.PRODUCTCOST, s.PRODUCTPRICE,
      $BATCH_TS, NULL, TRUE, FALSE,
      $BATCH_TS, $BATCH_TS
    FROM MS_ADWBI.WORK.TMP_PRODUCT s
    LEFT JOIN MS_ADWBI.WORK.DIM_PRODUCT d
      ON d.PRODUCTID = s.PRODUCTID
     AND d.CurrentFlag = TRUE
    WHERE d.PRODUCTID IS NULL
       OR (
           COALESCE(d.MODELNAME,'')           <> COALESCE(s.MODELNAME,'')
        OR COALESCE(d.PRODUCTDESCRIPTION,'')  <> COALESCE(s.PRODUCTDESCRIPTION,'')
        OR COALESCE(d.PRODUCTCOST, -1)        <> COALESCE(s.PRODUCTCOST, -1)
        OR COALESCE(d.PRODUCTPRICE, -1)       <> COALESCE(s.PRODUCTPRICE, -1)
       );
    
    -- SCD1 overwrite columns on current row
    UPDATE MS_ADWBI.WORK.DIM_PRODUCT d
    SET
      PRODUCTMODELID          = s.PRODUCTMODELID,
      PRODUCTSUBCATEGORYID    = s.PRODUCTSUBCATEGORYID,
      PRODUCT_SUBCATEGORY_SK  = s.PRODUCT_SUBCATEGORY_SK,
      PRODUCT_CATEGORY_SK     = s.PRODUCT_CATEGORY_SK,
      PRODUCTSKU              = s.PRODUCTSKU,
      PRODUCTNAME             = s.PRODUCTNAME,
      PRODUCTCOLOR            = s.PRODUCTCOLOR,
      PRODUCTSIZE             = s.PRODUCTSIZE,
      PRODUCTSTYLE            = s.PRODUCTSTYLE,
      WUpdateDate             = $BATCH_TS
    FROM MS_ADWBI.WORK.TMP_PRODUCT s
    WHERE d.PRODUCTID = s.PRODUCTID
      AND d.CurrentFlag = TRUE
      AND d.DeleteFlag  = FALSE
      AND (
           d.PRODUCTMODELID         IS DISTINCT FROM s.PRODUCTMODELID
        OR d.PRODUCTSUBCATEGORYID   IS DISTINCT FROM s.PRODUCTSUBCATEGORYID
        OR d.PRODUCT_SUBCATEGORY_SK IS DISTINCT FROM s.PRODUCT_SUBCATEGORY_SK
        OR d.PRODUCT_CATEGORY_SK    IS DISTINCT FROM s.PRODUCT_CATEGORY_SK
        OR d.PRODUCTSKU             IS DISTINCT FROM s.PRODUCTSKU
        OR d.PRODUCTNAME            IS DISTINCT FROM s.PRODUCTNAME
        OR d.PRODUCTCOLOR           IS DISTINCT FROM s.PRODUCTCOLOR
        OR d.PRODUCTSIZE            IS DISTINCT FROM s.PRODUCTSIZE
        OR d.PRODUCTSTYLE           IS DISTINCT FROM s.PRODUCTSTYLE
      );
    
    -- Deletes: mark deleted if product disappears from stage snapshot
    UPDATE MS_ADWBI.WORK.DIM_PRODUCT d
    SET
      DeleteFlag  = TRUE,
      CurrentFlag = FALSE,
      EndDateTime = $BATCH_TS,
      WUpdateDate = $BATCH_TS
    WHERE d.CurrentFlag = TRUE
      AND d.DeleteFlag  = FALSE
      AND NOT EXISTS (
        SELECT 1
        FROM MS_ADWBI.WORK.TMP_PRODUCT s
        WHERE s.PRODUCTID = d.PRODUCTID
      );$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_PRODUCT' SOURCE_TABLE_NAME,
    'MS_ADWBI' TARGET_DATABASE_NAME, 
    'WORK' TARGET_SCHEMA_NAME, 
    'DIM_PRODUCT' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_02' JOB_CODE,
    'REFRESH_PRODUCT_TABLE' JOB_NAME,
    4 STEP_NUMBER,
    'Create View for DIM_PRODUCT' STEP_DESC,
    $$CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_PRODUCT AS
    SELECT 
        PRODUCT_SK,
        PRODUCT_SUBCATEGORY_SK,
        PRODUCTSKU,
        PRODUCTNAME,
        MODELNAME,
        PRODUCTDESCRIPTION,
        PRODUCTCOLOR,
        PRODUCTSIZE,
        PRODUCTSTYLE,
        PRODUCTCOST,
        PRODUCTPRICE
    FROM MS_ADWBI.WORK.DIM_PRODUCT;$$ AS ETL_LOGIC,
    'MS_ADWBI' SOURCE_DATABASE_NAME,
    'WORK' SOURCE_SCHEMA_NAME,
    'DIM_PRODUCT' SOURCE_TABLE_NAME,
    'DATA_ACCESS' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'DIM_PRODUCT' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION

SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_03' JOB_CODE,
    'REFRESH_PRODUCT_CATEGORY_TABLE' JOB_NAME,
    1 STEP_NUMBER,
    'Truncate Table STG_PRODUCT_CATEGORY' STEP_DESC,
    $$TRUNCATE TABLE STAGE.MS_ADWBI.STG_PRODUCT_CATEGORY;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_PRODUCT_CATEGORY' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_PRODUCT_CATEGORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_03' JOB_CODE,
    'REFRESH_PRODUCT_CATEGORY_TABLE' JOB_NAME,
    2 STEP_NUMBER,
    'Insert Data to STG_PRODUCT_CATEGORY table from DATA_ACCESS Database' STEP_DESC,
    $$INSERT INTO STAGE.MS_ADWBI.STG_PRODUCT_CATEGORY
    SELECT
      PRODUCTCATEGORYID AS ProductCategoryID,
      NAME AS CategoryName
    FROM DATA_ACCESS.MS_PRODUCTION.V_PRODUCTCATEGORY;$$ AS ETL_LOGIC,
    'DATA_ACCESS' SOURCE_DATABASE_NAME,
    'MS_PRODUCTION' SOURCE_SCHEMA_NAME,
    'V_PRODUCTCATEGORY' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_PRODUCT_CATEGORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_03' JOB_CODE,
    'REFRESH_PRODUCT_CATEGORY_TABLE' JOB_NAME,
    3 STEP_NUMBER,
    'Insert Data to DIM_PRODUCT_CATEGORY table from STG_PRODUCT_CATEGORY Table using SCD1' STEP_DESC,
    $$-- DIM_PRODUCT_CATEGORY SCD1 upsert from STG_PRODUCT_CATEGORY
    SET BATCH_TS = CURRENT_TIMESTAMP();
    
    MERGE INTO MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY t
    USING (
      SELECT
        ProductCategoryID AS PRODUCTCATEGORYID,
        CategoryName      AS CATEGORYNAME
      FROM STAGE.MS_ADWBI.STG_PRODUCT_CATEGORY
    ) s
    ON t.PRODUCTCATEGORYID = s.PRODUCTCATEGORYID
    
    WHEN MATCHED THEN UPDATE SET
      t.CATEGORYNAME   = s.CATEGORYNAME,
      t.CurrentFlag    = TRUE,
      t.DeleteFlag     = FALSE,
      t.EndDateTime    = NULL,
      t.WUpdateDate    = $BATCH_TS
    
    WHEN NOT MATCHED THEN INSERT (
      PRODUCT_CATEGORY_SK,
      PRODUCTCATEGORYID,
      CATEGORYNAME,
      StartDateTime,
      EndDateTime,
      CurrentFlag,
      DeleteFlag,
      WInsertDate,
      WUpdateDate
    ) VALUES (
      MS_ADWBI.WORK.SEQ_DIM_PRODUCT_CATEGORY.NEXTVAL,
      s.PRODUCTCATEGORYID,
      s.CATEGORYNAME,
      $BATCH_TS,
      NULL,
      TRUE,
      FALSE,
      $BATCH_TS,
      $BATCH_TS
    );
    
    -- mark deletes
    UPDATE MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY t
    SET
      DeleteFlag   = TRUE,
      CurrentFlag  = FALSE,
      EndDateTime  = $BATCH_TS,
      WUpdateDate  = $BATCH_TS
    WHERE t.CurrentFlag = TRUE
      AND t.DeleteFlag = FALSE
      AND NOT EXISTS (
        SELECT 1
        FROM STAGE.MS_ADWBI.STG_PRODUCT_CATEGORY s
        WHERE s.ProductCategoryID = t.PRODUCTCATEGORYID
      );$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_PRODUCT_CATEGORY' SOURCE_TABLE_NAME,
    'MS_ADWBI' TARGET_DATABASE_NAME, 
    'WORK' TARGET_SCHEMA_NAME, 
    'DIM_PRODUCT_CATEGORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_03' JOB_CODE,
    'REFRESH_PRODUCT_CATEGORY_TABLE' JOB_NAME,
    4 STEP_NUMBER,
    'Create View for DIM_PRODUCT_CATEGORY' STEP_DESC,
    $$CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_PRODUCT_CATEGORY AS
    SELECT 
        PRODUCT_CATEGORY_SK,
        CATEGORYNAME
    FROM MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY;$$ AS ETL_LOGIC,
    'MS_ADWBI' SOURCE_DATABASE_NAME,
    'WORK' SOURCE_SCHEMA_NAME,
    'DIM_PRODUCT_CATEGORY' SOURCE_TABLE_NAME,
    'DATA_ACCESS' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'DIM_PRODUCT_CATEGORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION

SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_04' JOB_CODE,
    'REFRESH_PRODUCT_SUBCATEGORY_TABLE' JOB_NAME,
    1 STEP_NUMBER,
    'Truncate Table STG_PRODUCT_SUBCATEGORY' STEP_DESC,
    $$TRUNCATE TABLE STAGE.MS_ADWBI.STG_PRODUCT_SUBCATEGORY;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_PRODUCT_SUBCATEGORY' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_PRODUCT_SUBCATEGORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_04' JOB_CODE,
    'REFRESH_PRODUCT_SUBCATEGORY_TABLE' JOB_NAME,
    2 STEP_NUMBER,
    'Insert Data to STG_PRODUCT_SUBCATEGORY table from DATA_ACCESS Database' STEP_DESC,
    $$INSERT INTO STAGE.MS_ADWBI.STG_PRODUCT_SUBCATEGORY
    SELECT
      PRODUCTSUBCATEGORYID AS ProductSubCategoryID,
      PRODUCTCATEGORYID AS ProductCategoryID,
      NAME AS SubcategoryName
    FROM DATA_ACCESS.MS_PRODUCTION.V_PRODUCTSUBCATEGORY;$$ AS ETL_LOGIC,
    'DATA_ACCESS' SOURCE_DATABASE_NAME,
    'MS_PRODUCTION' SOURCE_SCHEMA_NAME,
    'V_PRODUCTSUBCATEGORY' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_PRODUCT_SUBCATEGORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_04' JOB_CODE,
    'REFRESH_PRODUCT_SUBCATEGORY_TABLE' JOB_NAME,
    3 STEP_NUMBER,
    'Insert Data to DIM_PRODUCT_SUBCATEGORY table from STG_PRODUCT_SUBCATEGORY Table using SCD1' STEP_DESC,
    $$-- DIM_PRODUCT_SUBCATEGORY SCD1 upsert from STG_PRODUCT_SUBCATEGORY
    SET BATCH_TS = CURRENT_TIMESTAMP();
    
    MERGE INTO MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY t
    USING (
      SELECT
        s.ProductSubCategoryID AS PRODUCTSUBCATEGORYID,
        s.ProductCategoryID    AS PRODUCTCATEGORYID,
        c.PRODUCT_CATEGORY_SK  AS PRODUCT_CATEGORY_SK,
        s.SubcategoryName      AS SUBCATEGORYNAME
      FROM STAGE.MS_ADWBI.STG_PRODUCT_SUBCATEGORY s
      JOIN MS_ADWBI.WORK.DIM_PRODUCT_CATEGORY c
        ON c.PRODUCTCATEGORYID = s.ProductCategoryID
       AND c.CurrentFlag = TRUE
       AND c.DeleteFlag  = FALSE
    ) s
    ON t.PRODUCTSUBCATEGORYID = s.PRODUCTSUBCATEGORYID
    
    WHEN MATCHED THEN UPDATE SET
      t.PRODUCTCATEGORYID   = s.PRODUCTCATEGORYID,
      t.PRODUCT_CATEGORY_SK = s.PRODUCT_CATEGORY_SK,
      t.SUBCATEGORYNAME     = s.SUBCATEGORYNAME,
      t.CurrentFlag         = TRUE,
      t.DeleteFlag          = FALSE,
      t.EndDateTime         = NULL,
      t.WUpdateDate         = $BATCH_TS
    
    WHEN NOT MATCHED THEN INSERT (
      PRODUCT_SUBCATEGORY_SK,
      PRODUCTSUBCATEGORYID,
      PRODUCTCATEGORYID,
      PRODUCT_CATEGORY_SK,
      SUBCATEGORYNAME,
      StartDateTime,
      EndDateTime,
      CurrentFlag,
      DeleteFlag,
      WInsertDate,
      WUpdateDate
    ) VALUES (
      MS_ADWBI.WORK.SEQ_DIM_PRODUCT_SUBCATEGORY.NEXTVAL,
      s.PRODUCTSUBCATEGORYID,
      s.PRODUCTCATEGORYID,
      s.PRODUCT_CATEGORY_SK,
      s.SUBCATEGORYNAME,
      $BATCH_TS,
      NULL,
      TRUE,
      FALSE,
      $BATCH_TS,
      $BATCH_TS
    );
    
    -- mark deletes
    UPDATE MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY t
    SET
      DeleteFlag   = TRUE,
      CurrentFlag  = FALSE,
      EndDateTime  = $BATCH_TS,
      WUpdateDate  = $BATCH_TS
    WHERE t.CurrentFlag = TRUE
      AND t.DeleteFlag = FALSE
      AND NOT EXISTS (
        SELECT 1
        FROM STAGE.MS_ADWBI.STG_PRODUCT_SUBCATEGORY s
        WHERE s.ProductSubCategoryID = t.PRODUCTSUBCATEGORYID
      );$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_PRODUCT_SUBCATEGORY' SOURCE_TABLE_NAME,
    'MS_ADWBI' TARGET_DATABASE_NAME, 
    'WORK' TARGET_SCHEMA_NAME, 
    'DIM_PRODUCT_SUBCATEGORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_04' JOB_CODE,
    'REFRESH_PRODUCT_SUBCATEGORY_TABLE' JOB_NAME,
    4 STEP_NUMBER,
    'Create View for DIM_PRODUCT_SUBCATEGORY' STEP_DESC,
    $$CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_PRODUCT_SUBCATEGORY AS
    SELECT 
        PRODUCT_SUBCATEGORY_SK,
        PRODUCT_CATEGORY_SK,
        SUBCATEGORYNAME
    FROM MS_ADWBI.WORK.DIM_PRODUCT_SUBCATEGORY;$$ AS ETL_LOGIC,
    'MS_ADWBI' SOURCE_DATABASE_NAME,
    'WORK' SOURCE_SCHEMA_NAME,
    'DIM_PRODUCT_SUBCATEGORY' SOURCE_TABLE_NAME,
    'DATA_ACCESS' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'DIM_PRODUCT_SUBCATEGORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION

SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_05' JOB_CODE,
    'REFRESH_TERRITORY_TABLE' JOB_NAME,
    1 STEP_NUMBER,
    'Truncate Table STG_TERRITORY' STEP_DESC,
    $$TRUNCATE TABLE STAGE.MS_ADWBI.STG_TERRITORY;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_TERRITORY' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_TERRITORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_05' JOB_CODE,
    'REFRESH_TERRITORY_TABLE' JOB_NAME,
    2 STEP_NUMBER,
    'Insert Data to STG_TERRITORY table from DATA_ACCESS Database' STEP_DESC,
    $$INSERT INTO STAGE.MS_ADWBI.STG_TERRITORY
    SELECT
      st.TERRITORYID AS TerritoryID,
      st.NAME        AS Region,
      cr.NAME        AS Country,
      st."GROUP"     AS Continent
    FROM DATA_ACCESS.MS_SALES.V_SALESTERRITORY st
    LEFT JOIN DATA_ACCESS.MS_PERSON.V_COUNTRYREGION cr
      ON cr.COUNTRYREGIONCODE = st.COUNTRYREGIONCODE;$$ AS ETL_LOGIC,
    'DATA_ACCESS' SOURCE_DATABASE_NAME,
    'MS_SALES | MS_PERSON' SOURCE_SCHEMA_NAME,
    'V_SALESTERRITORY | V_COUNTRYREGION' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_TERRITORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_05' JOB_CODE,
    'REFRESH_TERRITORY_TABLE' JOB_NAME,
    3 STEP_NUMBER,
    'Insert Data to DIM_TERRITORY table from STG_TERRITORY Table using SCD1' STEP_DESC,
    $$-- DIM_TERRITORY SCD1 upsert from STG_TERRITORY
    SET BATCH_TS = CURRENT_TIMESTAMP();
    
    MERGE INTO MS_ADWBI.WORK.DIM_TERRITORY t
    USING (
      SELECT DISTINCT
        TerritoryID,
        Region,
        Country,
        Continent
      FROM STAGE.MS_ADWBI.STG_TERRITORY
      WHERE TerritoryID IS NOT NULL
    ) s
    ON t.TERRITORYID = s.TerritoryID
    
    WHEN MATCHED THEN UPDATE SET
      t.Region       = s.Region,
      t.Country      = s.Country,
      t.Continent    = s.Continent,
      t.CurrentFlag  = TRUE,
      t.DeleteFlag   = FALSE,
      t.EndDateTime  = NULL,
      t.WUpdateDate  = $BATCH_TS
    
    WHEN NOT MATCHED THEN INSERT (
      TERRITORY_SK,
      TERRITORYID,
      Region,
      Country,
      Continent,
      StartDateTime,
      EndDateTime,
      CurrentFlag,
      DeleteFlag,
      WInsertDate,
      WUpdateDate
    ) VALUES (
      MS_ADWBI.WORK.SEQ_DIM_TERRITORY.NEXTVAL,
      s.TerritoryID,
      s.Region,
      s.Country,
      s.Continent,
      $BATCH_TS,
      NULL,
      TRUE,
      FALSE,
      $BATCH_TS,
      $BATCH_TS
    );
    
    -- mark deletes
    UPDATE MS_ADWBI.WORK.DIM_TERRITORY t
    SET
      DeleteFlag   = TRUE,
      CurrentFlag  = FALSE,
      EndDateTime  = $BATCH_TS,
      WUpdateDate  = $BATCH_TS
    WHERE t.CurrentFlag = TRUE
      AND t.DeleteFlag = FALSE
      AND NOT EXISTS (
        SELECT 1
        FROM STAGE.MS_ADWBI.STG_TERRITORY s
        WHERE s.TerritoryID = t.TERRITORYID
      );$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_TERRITORY' SOURCE_TABLE_NAME,
    'MS_ADWBI' TARGET_DATABASE_NAME, 
    'WORK' TARGET_SCHEMA_NAME, 
    'DIM_TERRITORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_05' JOB_CODE,
    'REFRESH_TERRITORY_TABLE' JOB_NAME,
    4 STEP_NUMBER,
    'Create View for DIM_TERRITORY' STEP_DESC,
    $$CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_TERRITORY AS
    SELECT 
        TERRITORY_SK,
        REGION,
        COUNTRY,
        CONTINENT
    FROM MS_ADWBI.WORK.DIM_TERRITORY;$$ AS ETL_LOGIC,
    'MS_ADWBI' SOURCE_DATABASE_NAME,
    'WORK' SOURCE_SCHEMA_NAME,
    'DIM_TERRITORY' SOURCE_TABLE_NAME,
    'DATA_ACCESS' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'DIM_TERRITORY' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION

SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_06' JOB_CODE,
    'REFRESH_CALENDAR_TABLE' JOB_NAME,
    1 STEP_NUMBER,
    'Truncate Table STG_CALENDAR' STEP_DESC,
    $$TRUNCATE TABLE STAGE.MS_ADWBI.STG_CALENDAR;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_CALENDAR' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_CALENDAR' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_06' JOB_CODE,
    'REFRESH_CALENDAR_TABLE' JOB_NAME,
    2 STEP_NUMBER,
    'Insert Data to STG_CALENDAR table from DATA_ACCESS Database' STEP_DESC,
    $$INSERT INTO STAGE.MS_ADWBI.STG_CALENDAR
    SELECT CALENDAR_DATE AS Date
    FROM DATA_ACCESS.MS_DATE.V_CALENDAR;$$ AS ETL_LOGIC,
    'DATA_ACCESS' SOURCE_DATABASE_NAME,
    'MS_DATE' SOURCE_SCHEMA_NAME,
    'V_CALENDAR' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_CALENDAR' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_06' JOB_CODE,
    'REFRESH_CALENDAR_TABLE' JOB_NAME,
    3 STEP_NUMBER,
    'Insert Data to DIM_CALENDAR table from STG_CALENDAR Table using SCD1' STEP_DESC,
    $$-- DIM_CALENDAR full reload from STG_CALENDAR
    SET BATCH_TS = CURRENT_TIMESTAMP();
    
    TRUNCATE TABLE MS_ADWBI.WORK.DIM_CALENDAR;
    
    INSERT INTO MS_ADWBI.WORK.DIM_CALENDAR
    (
      DATE_SK,
      CalendarDate,
      StartDateTime,
      EndDateTime,
      CurrentFlag,
      DeleteFlag,
      WInsertDate,
      WUpdateDate
    )
    SELECT
      TO_NUMBER(TO_CHAR(Date, 'MMDDYYYY')) AS DATE_SK,
      Date                                 AS CalendarDate,
      $BATCH_TS                            AS StartDateTime,
      NULL                                 AS EndDateTime,
      TRUE                                 AS CurrentFlag,
      FALSE                                AS DeleteFlag,
      $BATCH_TS                            AS WInsertDate,
      $BATCH_TS                            AS WUpdateDate
    FROM STAGE.MS_ADWBI.STG_CALENDAR;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_CALENDAR' SOURCE_TABLE_NAME,
    'MS_ADWBI' TARGET_DATABASE_NAME, 
    'WORK' TARGET_SCHEMA_NAME, 
    'DIM_CALENDAR' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_06' JOB_CODE,
    'REFRESH_CALENDAR_TABLE' JOB_NAME,
    4 STEP_NUMBER,
    'Create View for DIM_CALENDAR' STEP_DESC,
    $$CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.DIM_CALENDAR AS
    SELECT 
        DATE_SK,
        CALENDARDATE
    FROM MS_ADWBI.WORK.DIM_CALENDAR;$$ AS ETL_LOGIC,
    'MS_ADWBI' SOURCE_DATABASE_NAME,
    'WORK' SOURCE_SCHEMA_NAME,
    'DIM_CALENDAR' SOURCE_TABLE_NAME,
    'DATA_ACCESS' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'DIM_CALENDAR' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION

SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_07' JOB_CODE,
    'REFRESH_FACT_SALES_TABLE' JOB_NAME,
    1 STEP_NUMBER,
    'Truncate Table STG_FACT_SALES' STEP_DESC,
    $$TRUNCATE TABLE STAGE.MS_ADWBI.STG_FACT_SALES;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_FACT_SALES' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_FACT_SALES' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_07' JOB_CODE,
    'REFRESH_FACT_SALES_TABLE' JOB_NAME,
    2 STEP_NUMBER,
    'Insert Data to STG_FACT_SALES table from DATA_ACCESS Database' STEP_DESC,
    $$INSERT INTO STAGE.MS_ADWBI.STG_FACT_SALES
    SELECT
      ORDERDATE::DATE              AS ORDERDATE,
      STOCKDATE::DATE              AS STOCKDATE,
      ORDERNUMBER                  AS ORDERNUMBER,
      PRODUCTID::NUMBER(38,0)      AS PRODUCTID,
      CUSTOMERID::NUMBER(38,0)     AS BUSINESSENTITYID,
      TERRITORYID::NUMBER(38,0)    AS TERRITORYID,
      ORDERLINEITEM::NUMBER(38,0)  AS ORDERLINEITEM,
      ORDERQUANTITY::NUMBER(38,0)  AS ORDERQUANTITY,
      CURRENT_TIMESTAMP()          AS STG_LOAD_TS
    FROM DATA_ACCESS.MS_SALES.V_UDEMYSALES;$$ AS ETL_LOGIC,
    'DATA_ACCESS' SOURCE_DATABASE_NAME,
    'MS_SALES' SOURCE_SCHEMA_NAME,
    'V_UDEMYSALES' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_FACT_SALES' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_07' JOB_CODE,
    'REFRESH_FACT_SALES_TABLE' JOB_NAME,
    3 STEP_NUMBER,
    'Insert Data to FACT_SALES table from STG_FACT_SALES Table' STEP_DESC,
    $$-- FACT_SALES full reload from STG_FACT_SALES
    TRUNCATE TABLE MS_ADWBI.WORK.FACT_SALES;
    
    INSERT INTO MS_ADWBI.WORK.FACT_SALES
    (
      OrderDate_SK, StockDate_SK,
      OrderNumber, OrderLineItem,
      PRODUCT_SK, CUSTOMER_SK, TERRITORY_SK,
      OrderQuantity,
      WInsertDate, WUpdateDate
    )
    SELECT
      cal_o.DATE_SK AS OrderDate_SK,
      cal_s.DATE_SK AS StockDate_SK,
    
      s.ORDERNUMBER,
      s.ORDERLINEITEM,
    
      p.PRODUCT_SK,
      c.CUSTOMER_SK,
      t.TERRITORY_SK,
    
      s.ORDERQUANTITY,
    
      CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    FROM STAGE.MS_ADWBI.STG_FACT_SALES s
    LEFT JOIN MS_ADWBI.WORK.DIM_CALENDAR cal_o
      ON cal_o.CalendarDate = s.ORDERDATE
     AND cal_o.CurrentFlag = TRUE AND cal_o.DeleteFlag = FALSE
    LEFT JOIN MS_ADWBI.WORK.DIM_CALENDAR cal_s
      ON cal_s.CalendarDate = s.STOCKDATE
     AND cal_s.CurrentFlag = TRUE AND cal_s.DeleteFlag = FALSE
    LEFT JOIN MS_ADWBI.WORK.DIM_PRODUCT p
      ON p.PRODUCTID = s.PRODUCTID
     AND p.CurrentFlag = TRUE AND p.DeleteFlag = FALSE
    LEFT JOIN MS_ADWBI.WORK.DIM_CUSTOMER c
      ON c.BUSINESSENTITYID = s.BUSINESSENTITYID
     AND c.CurrentFlag = TRUE AND c.DeleteFlag = FALSE
    LEFT JOIN MS_ADWBI.WORK.DIM_TERRITORY t
      ON t.TERRITORYID = s.TERRITORYID
     AND t.CurrentFlag = TRUE AND t.DeleteFlag = FALSE;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_FACT_SALES' SOURCE_TABLE_NAME,
    'MS_ADWBI' TARGET_DATABASE_NAME, 
    'WORK' TARGET_SCHEMA_NAME, 
    'FACT_SALES' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_07' JOB_CODE,
    'REFRESH_FACT_SALES_TABLE' JOB_NAME,
    4 STEP_NUMBER,
    'Create View for FACT_SALES' STEP_DESC,
    $$CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.FACT_SALES AS
    SELECT 
        ORDERDATE_SK,
        STOCKDATE_SK,
        ORDERNUMBER,
        ORDERLINEITEM,
        PRODUCT_SK,
        CUSTOMER_SK,
        TERRITORY_SK,
        ORDERQUANTITY
    FROM MS_ADWBI.WORK.FACT_SALES;$$ AS ETL_LOGIC,
    'MS_ADWBI' SOURCE_DATABASE_NAME,
    'WORK' SOURCE_SCHEMA_NAME,
    'FACT_SALES' SOURCE_TABLE_NAME,
    'DATA_ACCESS' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'FACT_SALES' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION

SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_08' JOB_CODE,
    'REFRESH_FACT_RETURNS_TABLE' JOB_NAME,
    1 STEP_NUMBER,
    'Truncate Table STG_FACT_RETURNS' STEP_DESC,
    $$TRUNCATE TABLE STAGE.MS_ADWBI.STG_FACT_RETURNS;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_FACT_RETURNS' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_FACT_RETURNS' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_08' JOB_CODE,
    'REFRESH_FACT_RETURNS_TABLE' JOB_NAME,
    2 STEP_NUMBER,
    'Insert Data to STG_FACT_RETURNS table from DATA_ACCESS Database' STEP_DESC,
    $$INSERT INTO STAGE.MS_ADWBI.STG_FACT_RETURNS
    SELECT
      RETURNDATE::DATE             AS RETURNDATE,
      PRODUCTID::NUMBER(38,0)      AS PRODUCTID,
      TERRITORYID::NUMBER(38,0)    AS TERRITORYID,
      RETURNQUANTITY::NUMBER(38,0) AS RETURNQUANTITY,
      CURRENT_TIMESTAMP()          AS STG_LOAD_TS
    FROM DATA_ACCESS.MS_SALES.V_UDEMYRETURNS;$$ AS ETL_LOGIC,
    'DATA_ACCESS' SOURCE_DATABASE_NAME,
    'MS_SALES' SOURCE_SCHEMA_NAME,
    'V_UDEMYRETURNS' SOURCE_TABLE_NAME,
    'STAGE' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'STG_FACT_RETURNS' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_08' JOB_CODE,
    'REFRESH_FACT_RETURNS_TABLE' JOB_NAME,
    3 STEP_NUMBER,
    'Insert Data to FACT_RETURNS table from STG_FACT_RETURNS Table' STEP_DESC,
    $$-- FACT_RETURNS full reload from STG_FACT_RETURNS
    TRUNCATE TABLE MS_ADWBI.WORK.FACT_RETURNS;
    
    INSERT INTO MS_ADWBI.WORK.FACT_RETURNS
    (
      ReturnDate_SK,
      TERRITORY_SK,
      PRODUCT_SK,
      ReturnQuantity,
      WInsertDate, WUpdateDate
    )
    SELECT
      cal.DATE_SK AS ReturnDate_SK,
      t.TERRITORY_SK,
      p.PRODUCT_SK,
      r.RETURNQUANTITY,
      CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
    FROM STAGE.MS_ADWBI.STG_FACT_RETURNS r
    LEFT JOIN MS_ADWBI.WORK.DIM_CALENDAR cal
      ON cal.CalendarDate = r.RETURNDATE
     AND cal.CurrentFlag = TRUE AND cal.DeleteFlag = FALSE
    LEFT JOIN MS_ADWBI.WORK.DIM_TERRITORY t
      ON t.TERRITORYID = r.TERRITORYID
     AND t.CurrentFlag = TRUE AND t.DeleteFlag = FALSE
    LEFT JOIN MS_ADWBI.WORK.DIM_PRODUCT p
      ON p.PRODUCTID = r.PRODUCTID
     AND p.CurrentFlag = TRUE AND p.DeleteFlag = FALSE;$$ AS ETL_LOGIC,
    'STAGE' SOURCE_DATABASE_NAME,
    'MS_ADWBI' SOURCE_SCHEMA_NAME,
    'STG_FACT_RETURNS' SOURCE_TABLE_NAME,
    'MS_ADWBI' TARGET_DATABASE_NAME, 
    'WORK' TARGET_SCHEMA_NAME, 
    'FACT_RETURNS' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE
UNION 
SELECT 
    'ADVENTUREWORKS_REFRESH' PROJECT_NAME,
    'JOB_08' JOB_CODE,
    'REFRESH_FACT_RETURNS_TABLE' JOB_NAME,
    4 STEP_NUMBER,
    'Create View for FACT_RETURNS' STEP_DESC,
    $$CREATE OR REPLACE VIEW DATA_ACCESS.MS_ADWBI.FACT_RETURNS AS
    SELECT 
        RETURNDATE_SK,
        TERRITORY_SK,
        PRODUCT_SK,
        RETURNQUANTITY
    FROM MS_ADWBI.WORK.FACT_RETURNS;$$ AS ETL_LOGIC,
    'MS_ADWBI' SOURCE_DATABASE_NAME,
    'WORK' SOURCE_SCHEMA_NAME,
    'FACT_RETURNS' SOURCE_TABLE_NAME,
    'DATA_ACCESS' TARGET_DATABASE_NAME, 
    'MS_ADWBI' TARGET_SCHEMA_NAME, 
    'FACT_RETURNS' TARGET_TABLE_NAME,
    CURRENT_DATE() CREATED_DATE;

SELECT * FROM MS_ADWBI.CTRL.ADWBI_EXECUTE_PROCEDURES_MASTER_TABLE ORDER BY JOB_CODE,STEP_NUMBER;




























